### ISSUE TITLE
ImportError: cannot import name 'Seq2SeqOneStepDecoder'

### ISSUE THREAD

**Issue by yljylj** [dmlc/gluon-nlp#1002]
## Description
When I tried to run the train_gnmt.py, it got an error. I tried different version of gluonnlp including 0.6.0, 0.7.0, 0.7.1, 0.8.0 but it always got the same error.

### Error Message
Traceback (most recent call last):
  File "train_gnmt.py", line 48, in <module>
    from gnmt import get_gnmt_encoder_decoder
  File "/home/lujiayin/gluon-nlp/scripts/machine_translation/gnmt.py", line 24, in <module>
    from gluonnlp.model.seq2seq_encoder_decoder import Seq2SeqEncoder, Seq2SeqDecoder, \
ImportError: cannot import name 'Seq2SeqOneStepDecoder'

## To Reproduce
python gluon-nlp/scripts/machine_translation/train_gnmt.py

## What have you tried to solve it?

1. I tried to use different version of gluonnlp.

**Comment by leezu** [comment]
Where did you download the script?
You are using the development version of the script which relies on the unreleased GluonNLP 0.9. 
You can install the unreleased GluonNLP development version by cloning the repository and running `cd gluon-nlp; pip install --upgrade -e .'

**Comment by yljylj** [comment]
I downloaded the script by command 'git clone --recursive https://github.com/dmlc/gluon-nlp/'.
And now I tried to `cd gluon-nlp; pip install --upgrade -e .', but it got another compiling error.

[lujiayin@mlt-skx048 gluon-nlp]$ pip install --upgrade -e .
Obtaining file:///home/lujiayin/gluon-nlp
Requirement already satisfied, skipping upgrade: numpy in /home/lujiayin/anaconda3/lib/python3.6/site-packages (from gluonnlp==0.9.0.dev0) (1.16.3)
Requirement already satisfied, skipping upgrade: cython in /home/lujiayin/anaconda3/lib/python3.6/site-packages (from gluonnlp==0.9.0.dev0) (0.25.2)
Installing collected packages: gluonnlp
  Found existing installation: gluonnlp 0.8.0
    Uninstalling gluonnlp-0.8.0:
      Successfully uninstalled gluonnlp-0.8.0
  Running setup.py develop for gluonnlp
    ERROR: Complete output from command /home/lujiayin/anaconda3/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/lujiayin/gluon-nlp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps:
    ERROR: running develop
    running egg_info
    writing src/gluonnlp.egg-info/PKG-INFO
    writing dependency_links to src/gluonnlp.egg-info/dependency_links.txt
    writing requirements to src/gluonnlp.egg-info/requires.txt
    writing top-level names to src/gluonnlp.egg-info/top_level.txt
    /home/lujiayin/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /home/lujiayin/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py:331: UserWarning: Normalizing '0.9.0.dev' to '0.9.0.dev0'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'src/gluonnlp.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.py' under directory 'gluonnlp'
    warning: no previously-included files matching '*' found under directory 'tests'
    warning: no previously-included files matching '*' found under directory 'scripts'
    writing manifest file 'src/gluonnlp.egg-info/SOURCES.txt'
    running build_ext
    cythoning src/gluonnlp/data/wordpiece.pyx to src/gluonnlp/data/wordpiece.c
    building 'gluonnlp.data.wordpiece' extension
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lujiayin/anaconda3/include/python3.6m -c src/gluonnlp/data/wordpiece.c -o build/temp.linux-x86_64-3.6/src/gluonnlp/data/wordpiece.o
    src/gluonnlp/data/wordpiece.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    def tokenize(text: str, vocab: Dict[str, int], unknown_token: str, max_input_chars_per_word: cython.int = 200):
        """
        Cython implementation of single token tokenization. Average latency
        decreases to 95ms (from 144ms using original Python code).
        """
        output_tokens: List[str] = []
                    ^
    ------------------------------------------------------------

    src/gluonnlp/data/wordpiece.pyx:13:17: Syntax error in simple statement list
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of gluonnlp
  Moving to /home/lujiayin/anaconda3/lib/python3.6/site-packages/gluonnlp-0.8.0.dist-info/
   from /home/lujiayin/anaconda3/lib/python3.6/site-packages/~luonnlp-0.8.0.dist-info
  Moving to /home/lujiayin/anaconda3/lib/python3.6/site-packages/gluonnlp/
   from /home/lujiayin/anaconda3/lib/python3.6/site-packages/~luonnlp
ERROR: Command "/home/lujiayin/anaconda3/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/lujiayin/gluon-nlp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /home/lujiayin/gluon-nlp/

**Comment by yljylj** [comment]
I've successfully run the script by change the gluonnlp version to v0.7.0.

**Comment by leezu** [comment]
Can you please `pip install --upgrade --user cython` and post the output? Thank you!

**Comment by saekomdalkom** [comment]
Same error is occuring. Installation is not working.
