### ISSUE TITLE
prev_len in gpt.py

### ISSUE THREAD

**Issue by carter54** [dmlc/gluon-nlp#1015]
## Description
the gpt code in 
https://github.com/dmlc/gluon-nlp/blob/5e11334f5c00fd2875ab75c670b2595c560c30fc/scripts/text_generation/model/gpt.py#L258
seems to have a mistake.

I might be wrong, but I think the code `prev_len = states[0].shape[1]` means to return the length of previous key/value matrix (or the previous input tokens) . However it returns the number of multi-head (12 for the 124M gpt2 model).

### Error Message
NA

## To Reproduce
run scripts/text_generation/sequence_sampling.py script and print the output of `prev_len = states[0].shape[1]` at line 258 in scripts/text_generation/model/gpt.py.

## What have you tried to solve it?
1. change to `prev_len = states[0].shape[2]`

**Comment by leezu** [comment]
Then the positional embedding is calculated for the wrong positions

https://github.com/dmlc/gluon-nlp/blob/5e11334f5c00fd2875ab75c670b2595c560c30fc/scripts/text_generation/model/gpt.py#L262-L265

**Comment by leezu** [comment]
Added a fix to https://github.com/dmlc/gluon-nlp/pull/1010
@sxjscience please help to review.

**Comment by sxjscience** [comment]
Yes, it's a bug and it should be `states[0].shape[2]`

**Comment by sxjscience** [comment]
@carter54 Really appreciate for pointing out this!

**Comment by carter54** [comment]
@sxjscience happy to help! May I ask a question not related to this bug. Is there any method to accelerate the inference speed for gpt2 model? Can HybridBlock help? or quantization possibly?

**Comment by sxjscience** [comment]
Hybridization will definitely help. Quantization also helps but I’m not sure how to do that in MXNet. Another solution is to dump the Json file and use TVM for inference.

**Comment by carter54** [comment]
@sxjscience Thanks for your reply~ I read the TVM tutorial, most of the examples are within image processing area. Did you try TVM on gpt2 model before? Is there any examples and what range of the acceleration ratio can be expected? Thank you~
