### ISSUE TITLE
Better tokenizer for Chinese

### ISSUE THREAD

**Issue by sxjscience** [dmlc/gluon-nlp#102]
Currently, we support the MosesTokenizer in NLTK and the spaCy tokenizer. Both are not very good for tokenizing Chinese sentences. We could consider adding some Chinese tokenizers.

I've searched online and found these two candidates (There would be more):
1) Standford segmenter: https://nlp.stanford.edu/software/segmenter.html , http://www.nltk.org/_modules/nltk/tokenize/stanford_segmenter.html
2) Jieba tokenizer: https://github.com/fxsjy/jieba

We can add them in [transforms.py](https://github.com/dmlc/gluon-nlp/blob/master/gluonnlp/data/transforms.py).

**Comment by lixin4ever** [comment]
Can we create a tokenizer class only for Chinese here? Or still designing a general class (like **NLTKMosesTokenizer**) and setting the default "lang" as zh?

**Comment by sxjscience** [comment]
I think it’s a good solution.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
