### ISSUE TITLE
ERROR: Cannot determine archive format of /tmp/pip-req-build-layq6u4w

### ISSUE THREAD

**Issue by m0dulo** [dmlc/gluon-nlp#1036]
~/anaconda3/bin$ ./pip install gluonnlp https://pypi.tuna.tsinghua.edu.cn/simple
Collecting https://pypi.tuna.tsinghua.edu.cn/simple
  Using cached https://pypi.tuna.tsinghua.edu.cn/simple
  **ERROR: Cannot unpack file /tmp/pip-unpack-izb3uygg/simple (downloaded from /tmp/pip-req-build-layq6u4w, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-layq6u4w**
MxNet Version:1.5.0
Python Version:3.7.4

**Comment by leezu** [comment]
Please try without the Tsinghua setting. I think it's a problem with your mirror.

**Comment by CharlesLevis** [comment]
> 
> 
> Please try without the Tsinghua setting. I think it's a problem with your mirror.

**Comment by bGZoCg** [comment]
(By the way, the command needs the parameter `-i`, like that

```shell
./pip install gluonnlp -i https://pypi.tuna.tsinghua.edu.cn/simple
```
Anyway, that works for me.
