### ISSUE TITLE
example code for learning a vocabulary 

### ISSUE THREAD

**Issue by lilongyue** [dmlc/gluon-nlp#1040]
## Description
bert vocabulary tokens are directly downloaded but the code to generate a new vocabulary from plain text is not give.

Three ways are now available according to google team. [1]
1.Google's SentencePiece library
2.tensor2tensor's WordPiece generation script
3.Rico Sennrich's Byte Pair Encoding library

There is a tutorial on how to generate a bert-style vocabulary from SentencePiece lib. [2]

## References
[1]https://github.com/google-research/bert 
[2https://towardsdatascience.com/pre-training-bert-from-scratch-with-cloud-tpu-6e2f71028379]

**Comment by eric-haibin-lin** [comment]
Would this be helpful? http://gluon-nlp.mxnet.io/master/model_zoo/bert/index.html#custom-vocabulary 
Or is the discussion about adding a broader support for integrating other custom tokenization/vocabularies?

**Comment by lilongyue** [comment]
thanks!  ,this is really helpful!
