### ISSUE TITLE
Problem with gluon.utils.split_data

### ISSUE THREAD

**Issue by zburning** [dmlc/gluon-nlp#1061]
## Description
The current gluon.utils.split_data() has:
```
step = size // num_slice

# If size < num_slice, make fewer slices
if not even_split and size < num_slice:
        step = 1
        num_slice = size

if batch_axis == 0:
        slices = [data[i*step:(i+1)*step] if i < num_slice - 1 else data[i*step:size]
                  for i in range(num_slice)]
```

Considering an example:
we have a tensor of shape (31, *), and we want to split it into 8 slices. According to the function, step will be (31 // 8 = 3), so that the tensor will be split into 8 tensors of size [3, 3 ,3 ,3 ,3 ,3, 3, 10], in which the last tensor is extremely large. A better result could be [4, 4, 4, 4, 4, 4, 4, 3]

In many cases, we will have a batch size for model, for example, 32, and we wish each gpu to have a tensor of size 4. But within bucket sampler or in the last batch, it could be smaller, as exampled above, 31, then a tensor of size 10 can be to large in this case.

So I suggest to have step_size = ceil(size / num_slice), then the last slice will always be smaller. 

### Error Message
(Paste the complete error message, including stack trace.)

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by leezu** [comment]
Should this be an issue in the MXNet repo?

**Comment by zburning** [comment]
Yes, sorry, I will close this issue and move to the MXNet repo
