### ISSUE TITLE
Website and scripts/machine_translation/inference_transformer.py recommend different pretrained weights

### ISSUE THREAD

**Issue by leezu** [dmlc/gluon-nlp#1112]
## Description
https://github.com/dmlc/gluon-nlp/blame/3ce9995329fb0d18787019df541d4f229d7c9ded/scripts/machine_translation/inference_transformer.py#L169

uses `transformer_en_de_512_WMT2014-97ffd554a.zip`. But the [website](https://gluon-nlp.mxnet.io/master/model_zoo/machine_translation/index.html) recommends `transformer_en_de_512_WMT2014-e25287c5.zip`.

For consistency's sake we should use the same file on both sites.

Thanks @JulianSlzr for noting the issue in https://github.com/dmlc/gluon-nlp/issues/1038

@ciyongch @pengxin99 @eric-haibin-lin could you advise about why https://github.com/dmlc/gluon-nlp/pull/852 introduced the new parameter file?

**Comment by ciyongch** [comment]
@leezu Thanks for point out this, please check my answers in https://github.com/dmlc/gluon-nlp/pull/852, I will submit a PR to update the `inference_transformer.py` to use the same params as website recommends.

**Comment by ciyongch** [comment]
PR https://github.com/dmlc/gluon-nlp/pull/1117 was created for fixing this issue.
