### ISSUE TITLE
How to get the evaluation accuracy of BERT SQuAD 2.0

### ISSUE THREAD

**Issue by TaoLv** [dmlc/gluon-nlp#1125]
## Description
The fine-tuning process doesn't print the evaluation accuracy of BERT SQuAD 2.0.

```
INFO:gluonnlp:23:25:18 Time cost=19445.62 s, Thoughput=14.84 samples/s
INFO:gluonnlp:23:25:33 Loading dev data...
INFO:gluonnlp:23:25:33 Number of records in dev data:11873
INFO:gluonnlp:23:26:43 The number of examples after preprocessing:13600
Done! Transform dataset costs 11.57 seconds.
INFO:gluonnlp:23:26:43 start prediction
INFO:gluonnlp:23:30:07 Time cost=203.42 s, Thoughput=66.86 samples/s
INFO:gluonnlp:23:30:07 Get prediction results...
INFO:gluonnlp:23:31:27 Please run evaluate-v2.0.py to get evaluation results for SQuAD 2.0
```

Where  can I find the evaluate-v2.0.py?

### Error Message
None

## To Reproduce

```
python finetune_squad.py --optimizer adam --batch_size 8  --lr 3e-5 --epochs 2 --bert_model bert_24_1024_16 --version_2 --max_seq_length 256 --gpu 0  --null_score_diff_threshold -2.0
```

**Comment by zburning** [comment]
Hi, evaluate-v2.0.py is the official evaluation script. You can find it [here ](https://worksheets.codalab.org/rest/bundles/0x6b567e1cf2e041ec80d7098f031c5c9e/contents/blob/). To run BERT evaluation, you just need to specific --data_file and --pred_file.

**Comment by TaoLv** [comment]
Thank you @zburning. It would better if the script can be ported to gluon-nlp or sharing the url in the log message. Anyway, closing the issue now~

**Comment by leezu** [comment]
License seems unspecified. But @zburning let's link the file in the log message?
