### ISSUE TITLE
Include padding to fixed length in nlp.data.batchify

### ISSUE THREAD

**Issue by zburning** [dmlc/gluon-nlp#1132]
## Description
Sometimes we need to pad sequences to a fixed length for latency evaluation.
Does it make sense to include such a feature in nlp.data.batchify.Pad() or a new batchify API?

## References
- list reference and related literature
- list known implementations

**Comment by sxjscience** [comment]
I think previously we have the round-to feature in Pad(): https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/data/batchify/batchify.py#L179-L180 , which helps creating tensors that are suitable for tensorcore.

**Comment by leezu** [comment]
Reference https://github.com/dmlc/gluon-nlp/commit/5fe8d7b7f5770d82e4f3bfb489a67999d9442ce6#r36969715

**Comment by sxjscience** [comment]
I suggest adding a round_to argument to the script and compare the speed of round_to=8 and round_to=1.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
