### ISSUE TITLE
Docker container for GluonNLP

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#1139]
Looking at nvidia's [NGC container and their examples](https://github.com/NVIDIA/DeepLearningExamples/blob/master/MxNet/Classification/RN50v1.5/README.md#quick-start-guide), they made it really easy to run their example code and reproduce the environment and experiments. Having one for GluonNLP will make it easier for users

**Comment by leezu** [comment]
How about using AWS Deep Learning Containers for this purpose?

**Comment by sxjscience** [comment]
Added via https://github.com/dmlc/gluon-nlp/pull/1302
