### ISSUE TITLE
logging utils

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#1170]
https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/finetune_classifier.py#L191-L204
These common logging util function can be simplied as gluonnlp.util.set_logger(filename, level=INFO)

**Comment by sxjscience** [comment]
@eric-haibin-lin Currently I'm using logging_config: https://github.com/dmlc/gluon-nlp/blob/033214ec7eb7c36006bc3c6846220166b6bb5a00/src/gluonnlp/utils/misc.py#L174-L204
