### ISSUE TITLE
The frequent failure of CI for gpu-doc

### ISSUE THREAD

**Issue by StrayBird-ATSH** [dmlc/gluon-nlp#1185]
## Description
The CI for gpu-doc seems to be failing more frequent recently. As I look into the errors, they appear to be some specific place, see error message below.

### Error Message
Please see these CI errors.

It seems that there are three types of errors and these errors repeat randomly:
- wheel file cannot be downloaded
- python file existence error
- some baidu API error

https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1184/2/pipeline/

https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1179/4/pipeline/ 

https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1180/2/pipeline/

https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1180/3/pipeline/

https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1180/6/pipeline/

https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1180/7/pipeline/

https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1180/8/pipeline/

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. It seems that these errors have no relationship with what codes I commit. So they can be reproduced randomly.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by StrayBird-ATSH** [comment]
@eric-haibin-lin @leezu

**Comment by leezu** [comment]
Fix for the baidu file race condition: https://github.com/dmlc/gluon-nlp/pull/1187

**Comment by StrayBird-ATSH** [comment]
Thanks a lot for your fixing!

**Comment by StrayBird-ATSH** [comment]
Hello Leonard,
It seems there are some problem that are preventing us from building successfully?
It fails shortly after building.
Please see the log 
https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1191/3/pipeline
https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1191/2/pipeline
https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1186/2/pipeline
https://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-1186/1/pipeline

Thanks for your help! @leezu

**Comment by leezu** [comment]
/var/lib/jenkins//miniconda3/bin/python file disappeared on cpu-2 node. Maybe the filesystem is corrupt. I disabled the cpu-2 node for now

**Comment by leezu** [comment]
Please reopen if you experience more issues
