### ISSUE TITLE
Load custom pre-trained Fasttext model

### ISSUE THREAD

**Issue by Avi197** [dmlc/gluon-nlp#1206]
Does gluon-nlp support custom pre-trained Fasttext model? I want to use a few functions of gluon but i don't want to train a new model

Thanks in advance

**Comment by leezu** [comment]
You can use the https://github.com/dmlc/gluon-nlp/blob/3f7465ab5d0f926c2c6f424644daaa30668570ba/src/gluonnlp/model/train/embedding.py#L229
