### ISSUE TITLE
TextCNN rand model downloads pretrained vectors even if not needed

### ISSUE THREAD

**Issue by avinashsai** [dmlc/gluon-nlp#1217]
1. TextCNN rand model downloads pretrained word vectors even if not needed. rand model initializes word vectors randomly and updates in the training process. So, I think there is not need to download word vectors for this model. 

2. There should be a flag passed to ```_build_vocab```  function representing the type of model. If the model is other than rand, then pretrained vectors should be downloaded.

**Comment by avinashsai** [comment]
@leezu @eric-haibin-lin your thoughts on this?

**Comment by avinashsai** [comment]
@leezu I have code ready for this and iam able to reproduce the results as well. What do you think?

**Comment by leezu** [comment]
Yes, your proposal is sensible.

**Comment by avinashsai** [comment]
Sure, will submit PR to this

**Comment by avinashsai** [comment]
Fixed via #1222
