### ISSUE TITLE
albert model requested!

### ISSUE THREAD

**Issue by lilongyue** [dmlc/gluon-nlp#1221]
## Description
albert model size is pretty small and interesting. 
A mxnet based pretraining implementation should be helpful to alot of people!

**Comment by eric-haibin-lin** [comment]
@sxjscience is working on it

**Comment by sxjscience** [comment]
@lilongyue We have ALBERT in the new numpy version of GluonNLP, which is currently WIP and lives in a private repo. If you are very interested in that, we may contact offline to ensure that you can try it out.

**Comment by sxjscience** [comment]
@lilongyue You may try with the new version that is initiated in https://github.com/dmlc/gluon-nlp/pull/1225 . We are implementing the pretraining part and will PR once ready.
