### ISSUE TITLE
support vocab with indices assigned based on frequencies

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#131]
Currently, the indices in `gluonnlp.Vocab` are assigned in the following order:
- assign indices to special tokens, including: \<unk\>, \<pad\>, \<bos\>, \<eos\> and reserved ones
- assign indices to normal tokens in the counter. 

What I see missing for the language model in https://arxiv.org/pdf/1602.02410.pdf is the capability to do the following. For large scale language models that require sampling during training, it's important to build a vocab with indices generated based on word frequencies (including \<unk\>, \<eos\>, etc):
- assign indices to special & normal tokens based their frequency. 
- If a normal token's frequency is less than `min_freq`, its frequency should contribute to the frequency of \<unk\>.  

I propose we extend `gluonnlp.data.Counter` and introduce `gluonnlp.SortedVocab`:
#### Counter
- \_\_init\_\_(iterable, unknown_token=None, min_freq=None)

unknown_token: if specified, tokens whose freq is under `min_freq` contribute to the frequency of provided unknown_token. 

min_freq: if specified, tokens whose freq is under `min_freq` will be removed from the counter.

#### SortedVocab

- \_\_init\_\_(counter=None, max_size=None, min_freq=1, unknown_token=C.UNK_TOKEN,
                 padding_token=C.PAD_TOKEN, bos_token=C.BOS_TOKEN, eos_token=C.EOS_TOKEN,
                 reserved_tokens=None)

Indexing and embedding attachment for text tokens. The indices in the vocabulary is generated based on frequencies of the tokens, including special tokens (unk, pad, eos, bos and reserved tokens). If max_size is specified, special tokens are still guaranteed to be in the vocabulary. The provided counter instance is the source of all tokens' frequencies.

@leezu @sxjscience @szha

**Comment by szha** [comment]
A vocabulary class with explicit ordering of tokens based on a criteria sounds reasonable to me. Thanks for suggesting it.

one alternative to the proposed solution is that we can introduce a token_sort_key argument which takes a lambda function of form f(token)->object, and the vocab indices are then sorted by the value of the output of this function. The order can then be defined by this function.

**Comment by eric-haibin-lin** [comment]
Good point on the custom lambda function. However I don't think f(token) is sufficient in some cases. For my case it's rather f(token, counter) -> object.

**Comment by szha** [comment]
lambda f: counter[token]?

**Comment by szha** [comment]
you can carry arbitrary state in a function, including a counter.

**Comment by sxjscience** [comment]
Would it be better to just extend the Vocab class?

**Comment by eric-haibin-lin** [comment]
What about extending the existing vocab class like following:

Vocab(...., token_sort_key=None, ...)

- token_sort_key: a function: func(str) -> int

    When specified, the indices of all tokens (including special and reserved tokens) are generated based on the score produced by token_sort_key in descending order. The token_sort_key function takes a token as the input and produces a score as the output.

This means we no longer reserve index 0 for `<unk>`. 

@cgraywang @sxjscience @szha if everyone agrees this approach is better I'll update my PR

**Comment by szha** [comment]
@astonzhang

**Comment by astonzhang** [comment]
I think the use case is reasonable. Just be careful that we assume index of unknown token to be 0 in token_embedding, such as:

https://github.com/dmlc/gluon-nlp/blob/master/gluonnlp/embedding/token_embedding.py#L284
