### ISSUE TITLE
expose batch job logs as build artifacts

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#1341]
## Description
currently the batch job stdout/stderr outputs are dumped to the github actions worker. for easier debugging let's expose batch job logs as build artifacts

**Comment by sxjscience** [comment]
Also need to support codecov. After https://github.com/dmlc/gluon-nlp/pull/1337 is merged, we now support the "--runslow" option, which will only be turned on for the Batch instance. Thus, the codecov reduced significantly because there is no codecov uploaded.

**Comment by barry-jin** [comment]
closes via #1349
