### ISSUE TITLE
[AWS Batch Improvement] Having CPU Docker + GPU Docker

### ISSUE THREAD

**Issue by sxjscience** [dmlc/gluon-nlp#1342]
For dealing with CPU instance + GPU instance, one solution is to create two Dockerfile: one uses NVIDIA CUDA and the other one does not install CUDA.

Another solution is to create a requirements file and the user can specify additional requirements in https://github.com/dmlc/gluon-nlp/blob/master/tools/batch/docker/gluon_nlp_job.sh

**Comment by szha** [comment]
I described a solution to dependency management in #1340

**Comment by sxjscience** [comment]
@szha After a second thought, I think your proposal about adding a `requirements.txt` should be more appropriate. We can fix the version of MXNet to test by setting this file.

**Comment by sxjscience** [comment]
@szha @barry-jin Should be solved by https://github.com/dmlc/gluon-nlp/pull/1331/files . I added the dockerfile in https://github.com/dmlc/gluon-nlp/tree/master/tools/batch/docker
