### ISSUE TITLE
[Bug] [Typo] Fix convert_all.sh

### ISSUE THREAD

**Issue by sxjscience** [dmlc/gluon-nlp#1347]
Fix these two lines

https://github.com/dmlc/gluon-nlp/blob/e0b293e9ba515f8b4c58671232bd7c1b99522ebd/scripts/conversion_toolkits/convert_all.sh#L3-L4

`convert_bert_from_tf_hub.sh` --> `convert_bert.sh`
`convert_albert_from_tf_hub.sh` --> `convert_albert.sh`

**Comment by ZheyuYe** [comment]
Closed by https://github.com/dmlc/gluon-nlp/pull/1350
