### ISSUE TITLE
[CI] Increase the storage of GPU instance in CI

### ISSUE THREAD

**Issue by sxjscience** [dmlc/gluon-nlp#1361]
## Description
Currently, the GPU instance that is used for CI has the 10G space limit, which is not enough if we are going to test for the `gpt2_1558M` model added recently (https://github.com/dmlc/gluon-nlp/blob/c2e6d6080dd10b6b871de89d79c1d8fb81a7d3ec/src/gluonnlp/models/gpt2.py#L99-L107)

Thus, this is currently skipped in the test-case: https://github.com/dmlc/gluon-nlp/blob/c2e6d6080dd10b6b871de89d79c1d8fb81a7d3ec/tests/test_models_gpt2.py#L110

We may increase the space limit of the GPU instance and add this test case back.

**Comment by sxjscience** [comment]
@barry-jin Also, I noticed that there are some issues in terms of uploading the codecov report triggered by the `push` event https://codecov.io/gh/dmlc/gluon-nlp/commit/0e8664838be8c1a98af265bc992d766a7933f3fc

**Comment by barry-jin** [comment]
closes via #1375 and #1364
