### ISSUE TITLE
Wrong order of positional parameters in calls to Seq2SeqEncoder

### ISSUE THREAD

**Issue by logogin** [dmlc/gluon-nlp#1367]
## Description
`Seq2SeqEncoder` has next signature for the call:

```python
def __call__(self, inputs, valid_length=None, states=None)
```
but both child implementations, `TransformerEncoder` and `BERTEncoder` have signatures

```python
def __call__(self, inputs, states=None, valid_length=None)
```
i.e. flipped order of `states` and `valid_length` positions. Both implementations also call `super` with positional arguments.
The bug gets compensated by the fact that `Seq2SeqEncoder` simply passes through parameters without transformation and parameters flip back to the original positions.

**Comment by sxjscience** [comment]
@logogin I think this should have been solved via https://github.com/dmlc/gluon-nlp/pull/1368 so I closed the issue.
