### ISSUE TITLE
[doc] File is missing in the README.md

### ISSUE THREAD

**Issue by TristonC** [dmlc/gluon-nlp#1380]
The `prepare_bookcorpus.py` file is missing on this README.md  https://github.com/dmlc/gluon-nlp/tree/master/scripts/datasets/pretrain_corpus
(It should have been renamed `prepared_gutenberg.py`, and in which case the parameters need to be changed).
```
python3 prepare_bookcorpus.py --dataset gutenberg
```

@sxjscience

**Comment by sxjscience** [comment]
Thanks! A really nice catch!

**Comment by sxjscience** [comment]
@TristonC This is fixed via https://github.com/dmlc/gluon-nlp/pull/1378 so I'll close this.
