### ISSUE TITLE
[Tokenizer] Upgrade tokenizers to the latest

### ISSUE THREAD

**Issue by sxjscience** [dmlc/gluon-nlp#1431]
## Description
Currently we are fixing the tokenizers package to 0.8.1: https://github.com/dmlc/gluon-nlp/blob/84391ef90b5926ff2186c1931cfb460b7fc3785e/setup.py#L47

However, the huggingface/tokenizers have been recently upgraded to 0.9.4. Thus, we may consider to support the latest version.

## References
- https://github.com/huggingface/tokenizers

**Comment by sxjscience** [comment]
The related code base is here: https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/data/tokenizers/huggingface.py

**Comment by barry-jin** [comment]
Closed via #1444
