### ISSUE TITLE
[Tests] It takes long time to test full suite of backbone models

### ISSUE THREAD

**Issue by barry-jin** [dmlc/gluon-nlp#1445]
## Description
It takes about 6 hours to run pytest on test_models, which has blocked GluonNLP CI. This problem exists on and after MXNet nightly build 20201120. 

### Error Message
<img width="1210" alt="Screen Shot 2020-11-23 at 1 47 45 PM" src="https://user-images.githubusercontent.com/69359374/100131819-62c4a480-2e39-11eb-9283-b12f1da1396a.png">

**Comment by sxjscience** [comment]
What's added in 20201120?

**Comment by barry-jin** [comment]
> What's added in 20201120?

For current GluonNLP master, it will take 17 min to test backbone models on MXNet nightly build before 20201120, but will take 6 hours to run the same tests on MXNet nightly build on and after 20201120. On Nov 20, I only find one commit https://github.com/apache/incubator-mxnet/commit/13e9d572b3059ebe0d1d4f6d452db4f971375588

**Comment by leezu** [comment]
> nightly build before 20201120

What day is the build?

**Comment by barry-jin** [comment]
> > nightly build before 20201120
> 
> What day is the build?

I tried both `mxnet-cu102==2.0.0b20201118` and `mxnet-cu102==2.0.0b20201119`, the pytest on test_models will take only 17 min. 

To Reproduce
```
python3 ./tools/batch/submit-job.py --region us-east-1 \
                                    --job-type g4dn.4x \
                                    --name GluonNLP-GPU-Test-Try-test_models \
                                    --source-ref npx.savez \
                                    --work-dir . \
                                    --remote https://github.com/leezu/gluon-nlp \
                                    --command "pip3 uninstall -y mxnet-cu102 && python3 -m pip install -U --quiet --pre "mxnet-cu102==2.0.0b20201119" -f https://dist.mxnet.io/python && python3 -m pip install pytest-forked && python3 -m pytest --forked --cov=. --cov-config=./.coveragerc --cov-report=xml --durations=50 --device="gpu" --verbose --runslow ./tests/test_models.py" \
                                    --wait
```

**Comment by leezu** [comment]
Will be fixed by https://github.com/apache/incubator-mxnet/pull/19584
