### ISSUE TITLE
BERT/Eelectra vocab file and tokenizer model. 

### ISSUE THREAD

**Issue by araitats** [dmlc/gluon-nlp#1451]
## Description
The default **learn_subword** returns special tokens with "<unk>", "<s>", "</s>", and "<pad>". By convention, BERT uses [UNK] [PAD] [CLS] [SEP] and [MASK]. How can we define **--custom-special-tokens** flag so that the tokenizer model and vocab file have these BERT special tokens?  What is the best practice for that? 

## References
- list reference and related literature
- list known implementations

**Comment by sxjscience** [comment]
@araitats This should have been solved. I'll close this issue.
