### ISSUE TITLE
Incorrect link to the mentioned book in the README.rst file

### ISSUE THREAD

**Issue by realBjornRoden** [dmlc/gluon-nlp#1465]
## Description
The link to the mentioned book seem to be incorrect at the end of the file https://github.com/dmlc/gluon-nlp/blob/v0.10.x/README.rst

Should probably be https://d2l.ai/d2l-en.pdf but is http://en.diveintodeeplearning.org/

**Comment by szha** [comment]
@realBjornRoden many thanks for letting us know. I fixed the link just now and will port the fix to other release branches.

**Comment by sxjscience** [comment]
Close because it has been fixed in the v0.x branch.
