### ISSUE TITLE
nlp.models.bert.get_pretrained_bert provides slow tokenizer

### ISSUE THREAD

**Issue by leezu** [dmlc/gluon-nlp#1538]
LegacyHuggingFaceTokenizer instead of https://github.com/huggingface/tokenizers

**Comment by sxjscience** [comment]
I think both are using tokenizers but the legacy one is following the API of an older version of HF tokenizers.

**Comment by leezu** [comment]
The ` transformers.PreTrainedTokenizer` is "Base class for all slow tokenizers." compared to ` transformers.PreTrainedTokenizerFast` which is "Base class for all fast tokenizers (wrapping HuggingFace tokenizers library)." so only the latter uses HF tokenizers

**Comment by sxjscience** [comment]
We are calling the `tokenizers` package directly in the implementation.
