### ISSUE TITLE
[DISCUSS] How do we reorganize the homepage for easier feature discovery

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#156]
right now it's not obvious what is available, especially lots of the code are in scripts. as a starter, here are some ideas:
1. rename scripts to Toolkits, and list them in the home page
2. split the scripts into their individual pages instead of one unified page

**Comment by szhengac** [comment]
"Toolkit" may be confusing with Gluon nlp toolkit. But sure it is better to have a hierarchical structure.

**Comment by szha** [comment]
Let's keep the "Scripts" name then. We definitely need nicer page layouts for them.
