### ISSUE TITLE
I want BigRNN back...

### ISSUE THREAD

**Issue by yifeim** [dmlc/gluon-nlp#1577]
## Description
There are some good ideas in this model:

https://nlp.gluon.ai/_modules/gluonnlp/model/language_model.html#BigRNN

Where is it in the codebase now? If it is not in the codebase anymore, are there any conflicts causing it to be removed? Can they be resolved?

Thanks.

**Comment by szha** [comment]
Hi @yifeim. The main reason they are not added back yet is that we don't have people who maintain the sparse features in MXNet that are used in this class yet. As soon as we have someone pick that up, we will be able to add these blocks back.

**Comment by yifeim** [comment]
Hmm. I'd like to know more about the sparse maintenance challenge. I am not a C expert, but I think it might be nice to make the issues more transparent in search of potential helps.

**Comment by yifeim** [comment]
Hi @szha Actually, I just realized that you meant mxnet-2.x. Sure. mxnet-1.x may still be around for some time, while mxnet-2.x is being made to perfect. Should I look at version v0.10.x as the last version that supports mxnet-1.x?

**Comment by szha** [comment]
Yes, the sparse features are still available there.

**Comment by yifeim** [comment]
Thanks. Will close this comment with a link to v0.10.x branch: https://github.com/dmlc/gluon-nlp/tree/v0.10.x
