### ISSUE TITLE
beam search early stop

### ISSUE THREAD

**Issue by hhexiy** [dmlc/gluon-nlp#171]
Feature request:
Stop search after beam_size EOS generated in the beam.

**Comment by szhengac** [comment]
Our implementation has already taken this into account. See https://github.com/dmlc/gluon-nlp/blob/93dad9ef397c2ad31f828eea16797f7e536a6da8/gluonnlp/model/beam_search.py#L225-L227

**Comment by hhexiy** [comment]
ok, thanks!
