### ISSUE TITLE
gluonnlp.batchify.Stack() does not accept input parameter

### ISSUE THREAD

**Issue by cyrusmvahid** [dmlc/gluon-nlp#229]
According to the code base in `gluonnlp.data.batchify` , `Stack()` should be able to take` dtype` as input if run on a jupyter notebook

```
import gluonnlp 
import numpy as mp
gluonnlp.data.batchify.Stack(dtype=np.float32)
```
Running the  above code in notebook results in:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-fbef5d961433> in <module>()
      1 import gluonnlp
      2 import numpy as mp
----> 3 gluonnlp.data.batchify.Stack(dtype=np.float32)

TypeError: object() takes no parameters`

```

However, the same code works fine on PyCharm

result of the same code on PyCharm, remotely connected to the same EC2 instance is:
```
<gluonnlp.data.batchify.Stack object at 0x7febbacade80>
```

# environment

```
mxnet: 1.3.0
gluonnlp:   INSTALLED: 0.3.2 (latest)
```

# Jupyter version:
```
packages in environment at /home/ubuntu/anaconda3/envs/mxnet_p36:
Name                    Version                   Build  Channel
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge

```

**Comment by szha** [comment]
Hi Cyrus. Is it possible that you have multiple versions of gluonnlp installed? For example, is it possible that your jupyter kernel is using a different copy? I can indeed find the dtype argument in Stack https://github.com/dmlc/gluon-nlp/blob/2ca508fbeb156343fc0730f0e74ed6804417aa09/gluonnlp/data/batchify.py#L131

**Comment by cyrusmvahid** [comment]
gluonnlp.__version__ is 0.3.2 on both environments
```
if __name__ == "__main__":
    print(nlp.__version__)
    print(mx.__version__)
```
0.3.2
1.3.0 but now the problem is gone. I must have upgraded jupyter env as ran pip commands in there
Sorry for the false alarm
