### ISSUE TITLE
Unify bptt_batchify interface between LanguageModelStream and LanguageModelDataset

### ISSUE THREAD

**Issue by leezu** [dmlc/gluon-nlp#245]
Currently there are at least the following discrepancies:

- `LanguageModelStream.bptt_batchify()` returns a mask
  - The mask can be recovered by `mask = data != vocab[vocab.padding_token]`
  - We can either change the `LanguageModelDataset.bptt_batchify()` interface to also return a mask or use above formula to recover there mask where neede.
  - I vote for above formula, as it explicitly defines the mask and may be clearer to users. Users anyways need a line `mask = mask.as_in_context(ctx)` which could then just be replaced by `mask = data != vocab[vocab.padding_token]`. However, I'd also be ok with chaning the `LanguageModelDataset.bptt_batchify()`.
  - `LanguageModelStream.bptt_batchify()` is smart and never includes `<eos>` in the data batch but only in the target  batch.
  - `LanguageModelDataset.bptt_batchify()` instead assumes the data doesn't contain `<bos>` but only `eos`.
  - See https://github.com/dmlc/gluon-nlp/blob/master/gluonnlp/data/stream.py#L415

@cgraywang @szha @eric-haibin-lin

**Comment by szha** [comment]
I think it would be good to make the interface and skip behavior consistent. On that, I think it's a good time to bring up again #128 (which was reverted in #134). The interface would become clean in two ways:
1. corpora are just corpora. they are arbitrary text and they don't have to have specific format for samples
2. batchify is a clean way to abstract the BPTT logic, as the function abstraction is already used such as Stack() and Pad(). If we follow this abstraction, we won't need to maintain separate functions for stream and dataset.

**Comment by cgraywang** [comment]
Based on offline discussion with Leo @leezu  , I think it is reasonable to align the bptt_batchify return value between datastream and corpus dataset. Then let's remove the mask as the return value, and only preserve data and target as the return value. Thanks @leezu

**Comment by leezu** [comment]
https://github.com/dmlc/gluon-nlp/pull/246 serves to illustrate the changes suggested here to unify the API (not taking into account #128, which indeed should be revisited, thanks @szha). @szha @eric-haibin-lin please double check and raise any concerns. I'm happy to adapt the code there if you prefer any other way to align the API.

**Comment by leezu** [comment]
Fixed by #282
