### ISSUE TITLE
ConvolutionalEncoder: contradictory description of parameter `conv_layer_activation`

### ISSUE THREAD

**Issue by bikestra** [dmlc/gluon-nlp#263]
https://github.com/dmlc/gluon-nlp/blob/ca071a6dfd7ad729a50127d1e43afe417b3230b6/gluonnlp/model/convolutional_encoder.py#L63-L66

The docstring says that if nothing is specified for `conv_layer_activation`, no activation will be applied; however, the default is `tanh`, so `tanh` will be applied if nothing was specified. I don't think Kim et. al paper applies any activation, so the default value of this parameter should be `linear` in order to be consistent with the rest of the documentation.

Maybe I misinterpreted the docstring, but it's at least confusing.

**Comment by bikestra** [comment]
Sorry, Kim et al do use `tanh`.

**Comment by leezu** [comment]
https://github.com/yoonkim/lstm-char-cnn/blob/master/model/TDNN.lua#L27

**Comment by bikestra** [comment]
Yes, they use `tanh`, but then shouldn't the description of the default behavior be changed?

**Comment by leezu** [comment]
Thanks for pointing out the docstring issue and no worries regarding `tanh`.  I agree we should change the docstring. Do you want to open a PR to change it?
If so, you may also wish to add 
```
 seq.add(nn.Activation(conv_layer_activation))
```

to 

```
if conv_layer_activation is not None:
    seq.add(nn.Activation(conv_layer_activation))
```
or similar in 
https://github.com/dmlc/gluon-nlp/blob/ca071a6dfd7ad729a50127d1e43afe417b3230b6/gluonnlp/model/convolutional_encoder.py#L117

**Comment by bikestra** [comment]
OK, I will open a PR.
