### ISSUE TITLE
wrong table format

### ISSUE THREAD

**Issue by mli** [dmlc/gluon-nlp#267]
see http://gluon-nlp.mxnet.io/scripts/index.html

<img width="227" alt="screen shot 2018-08-10 at 1 24 40 pm" src="https://user-images.githubusercontent.com/421857/43979839-e2fa795e-9ca0-11e8-93cd-0a23eabf21d5.png">

**Comment by szha** [comment]
@mli this is already fixed in master and it will be addressed when we make the next release (likely in the following week)

**Comment by szha** [comment]
fixed
