### ISSUE TITLE
Sharded dataloader causing CI hangs

### ISSUE THREAD

**Issue by leezu** [dmlc/gluon-nlp#274]
Recently many jobs on CI are running into deadlocks and must be manually killed. This morning I killed a few jobs that ran more than 12 hours. I observe that all of them hang in the sharded dataloader tests. @szhengac do you have any idea what could be the reason?

From http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-246/10/pipeline
```
tests/unittest/train/test_dataloader.py::test_sharded_data_loader Sending interrupt signal to process
```

Also
- http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-233/25/pipeline/
- http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-246/12/pipeline/

**Comment by szhengac** [comment]
Does script have the same problem? Is it possible that it is due to some
env setup changes? I think we don’t have such problems before.

**Comment by leezu** [comment]
I'm not aware of any change in environment. It may be due to some other issue, but for some reason CI always shows that it was working on the sharded dataloader test when being killed.

**Comment by leezu** [comment]
I think the hang also occurs during the test_transformer scripts tests as it relies on the ShardedDataloader. ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-275/2/pipeline/22 
I disabled that for now too.

**Comment by leezu** [comment]
CI works again after disabling both. The test should be enabled again before 0.4

**Comment by szhengac** [comment]
I think this is due to the recent change in DataLoader (#11908). The shared DataLoader inherits the DataLoader, and the change possibly incurs some inconsistency. The workaround is to copy the original DataLoader to shared Dataloader instead of using inheritance.

**Comment by szha** [comment]
@zhreshold may have some ideas.
