### ISSUE TITLE
GBW vocab needs update

### ISSUE THREAD

**Issue by leezu** [dmlc/gluon-nlp#291]
#282 unified the BPTT interface. GBW before used both `<eos>` and `<bos>`. But #282 didn't update the default vocabulary file downloaded from S3. The vocabulary needs to be updated to remove `<bos>` as otherwise the sampling weights won't be correct, which seems to result in 0.5 higher train PPL.

**Comment by szha** [comment]
WIP

**Comment by szha** [comment]
addressed in #294
