### ISSUE TITLE
Model Zoo Page

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#325]
We currently have several pre-trained language models, but there's no list of content for the model zoo. As we have more and more pre-trained models, we can consider:
- move pre-defined models into a model_zoo module.
- have a page to summarize what pre-trained models are available.
- allow people to contribute pre-defined models and pre-trained parameters more easily.

**Comment by NonvolatileMemory** [comment]
I agree.
Like the transformer ["attention is all you need"] needs so much time and resource to train, if gluon-nlp can offer the pre-trained parameters it would be very good.

**Comment by NonvolatileMemory** [comment]
need some contributors?

**Comment by szha** [comment]
We will need a new encoder-decoder interface (#265) and to do some refactoring, after which we can move the model definition into our API and start sharing pre-trained weights.

**Comment by szha** [comment]
In the meantime, we have the weights on WMT14 EN-DE at http://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/transformer_en_de_512_WMT2014-14bd361b.zip. If you're accessing it from China, it might be faster with this link instead: https://apache-mxnet.s3.cn-north-1.amazonaws.com.cn/gluon/models/transformer_en_de_512_WMT2014-14bd361b.zip

**Comment by szha** [comment]
@szhengac for now, shall we provide these links in the scripts page instead?

**Comment by szhengac** [comment]
@szha. Sure, We can provide the links in the scripts page.

**Comment by eric-haibin-lin** [comment]
Bounce. Is there a decision on the encoder-decoder interface?

**Comment by szha** [comment]
That's tracked in #265

**Comment by leezu** [comment]
The pre-trained embeddings available in GluonNLP should also be listed (see https://github.com/dmlc/gluon-nlp/issues/329#issuecomment-431621714 )

**Comment by szha** [comment]
Model zoo page is now available. @leezu I'm tracking the listing of embeddings in #396 instead
