### ISSUE TITLE
why dtype=int32? 

### ISSUE THREAD

**Issue by whamza15** [dmlc/gluon-nlp#346]
SequenceMask, SequenceReverse, and SequenceLast all expect valid_length to be float32. It requires casting to float32. I am not sure how expensive casting is but any reason this is int32? Maybe we can make this an option as well?

https://github.com/dmlc/gluon-nlp/blob/7a10dca33b4e0684eee5198c447afeec22659ea3/gluonnlp/data/batchify/batchify.py#L73

**Comment by szha** [comment]
For large input/output space, float32 cannot represent int32 accurately, since float32 has fewer mantissa bits than int32. I think we should extend the sequence operators to more types.

**Comment by whamza15** [comment]
@szha I am actually surprised that sequence operators are acting on float32 in the first place. I am sure there is a reason. But I can't think of one

**Comment by szha** [comment]
likely just legacy

**Comment by whamza15** [comment]
Should I create an issue on mxnet?

**Comment by szha** [comment]
@whamza15 I created one here: https://github.com/apache/incubator-mxnet/issues/12649

**Comment by szha** [comment]
This issue is tracked at upstream.
