### ISSUE TITLE
Please update slack invitation link

### ISSUE THREAD

**Issue by Lucid-Network** [dmlc/gluon-nlp#355]
Hello,

i'd like to join the community on slack, but the invitation link has expired.

Please generate a new one.

thx!

**Comment by szha** [comment]
I'm updating it in #356

**Comment by szha** [comment]
The pull request is merged. The updated link is https://join.slack.com/t/apache-mxnet/shared_invite/enQtNDQyMjAxMjQzMTI3LTkzMzY3ZmRlNzNjNGQxODg0N2Y5NmExMjEwOTZlYmIwYTU2ZTY4ZjNlMmEzOWY5MGQ5N2QxYjhlZTFhZTVmYTc.
The default website page currently points to 0.4.0 release. We are preparing 0.4.1 release which will happen soon, at which time the link on the default website will be updated.

**Comment by Lucid-Network** [comment]
thx!
