### ISSUE TITLE
Remove unnecessary use of pickle in nmt script

### ISSUE THREAD

**Issue by leezu** [dmlc/gluon-nlp#361]
As discussed at https://github.com/dmlc/gluon-nlp/pull/350#issuecomment-425624336 to reduce runtime of caching code from ~80 seconds to ~4 seconds and reduce disk space requirements by 40%. This will improve the user experience.

**Comment by szha** [comment]
Fixed in #400

**Comment by szha** [comment]
good catch. I will patch it in 403
