### ISSUE TITLE
subword methods (BPE/wordpiece)

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#374]
I'd like to start a discussion on how we integrate subword methods such as BPE and wordpiece.

I've been working on some BPE tokenization with https://github.com/google/sentencepiece and have been quite happy with it. It provides pip packages on all platforms and is shipped with the binary inside. It carries an apache 2.0 license.

The places where subword methods are needed are subword functions in vocab and tokenizer/detokenizer.

cc @leezu @szhengac

**Comment by szha** [comment]
The encode function in sentencepiece supports both returning the token and returning the index, which conforms to our tokenizer interface and vocab interface, respectively.

**Comment by szhengac** [comment]
I think subword methods needs to be separated from tokenizer/detokenizer, because tokenizer/detokenizer is data independent, while learning BPE/wordpiece is data dependent. In general, the learning of subwords is performed after the tokenization.

**Comment by szha** [comment]
#380

**Comment by szha** [comment]
We got the sentencepiece integration now. For subword-nmt, I haven't picked this up yet so it's unlikely I will get to it in 0.5.0.

**Comment by leezu** [comment]
I intend to add a wrapper for https://github.com/VKCOM/YouTokenToMe
