### ISSUE TITLE
machine translation notebooks need improvement

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#399]
Problems:
- Large amount of duplicate in transformer notebooks from GNMT notebook. As a result, user may experience dejavu.
  - Recommendation: wrap these duplicate parts into functions, introduce them once in GNMT notebook, and reuse the function.
- Length. The machine translation notebooks are very long. This is partly due to the duplicate problem. However, trying to cover many things in one place contributes to it too.
  - Recommendation: split the notebook into two parts. One is for using pre-trained models and can focus on inference. Then create a separate notebook to include **simplified** training logic. At the end, refer users to the model zoo in which full-fledged training scripts can be found.
- Lack of explanation. The writing around the code blocks doesn't provide enough help for new users to go through the code.
  - Recommendation: treat tutorials as an opportunity for users to understand how to use the API by providing meaningful comments and description on the functionality.
- Lack of links to API.
  - Recommendation: notebooks should be link-rich so that users can easily refer to the API documentation when trying to understand what the code does.

**Comment by szha** [comment]
Addressed transformer notebook in https://github.com/dmlc/gluon-nlp/pull/400.

The training part of the tutorial saved at https://gist.github.com/szha/ffde8760d2ed296c5022dfed6a04fbb9, which is to be used to make a separate tutorial.

Given that transformer notebook is in a reasonable shape, I'm counting this part of effort done for 0.5.0 release. I'm still keeping the issue alive to track the rest of the changes.

**Comment by eric-haibin-lin** [comment]
Is this already done?
