### ISSUE TITLE
Document Dataset & Transformation Return Type (prev: Need better documentation for gluonnlp.data.* )

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#405]
Many datasets don't document the return types, which makes it hard for others to understand how to use the API. We should at least document return types, and if possible at examples. 

- [x] DataStream
- [x] SimpleDataStream
- [x] DatasetStream
- [x] ClipSequence
- [x] PadSequence
- [x] NLTKMosesTokenizer
- [x] SacreMosesTokenizer
- [x] SpacyTokenizer
- [x] SacreMosesDetokenizer
- [x] NLTKMosesDetokenizer
- [x] MEN @eric-haibin-lin (#605)
- [x] PrefetchingStream @eric-haibin-lin 
- [ ] GBWStream @eric-haibin-lin 
- [ ] SimpleDatasetStream
- [ ] IWSLT2015
- [ ] WMT2014
- [ ] WMT2014BPE
- [ ] WMT2016
- [ ] WMT2016BPE
- [ ] TextLineDataset
- [ ] CorpusDataset

## #614
- [x] WikiText2 @szha
- [x] WikiText103 @szha
- [x] WikiText2Raw @szha
- [x] WikiText103Raw @szha
- [x] CoNLL2000 @szha
- [x] CoNLL2001 @szha
- [x] CoNLL2002 @szha
- [x] CoNLL2004 @szha
- [x] UniversalDependencies21 @szha
- [x] IMDB @szha
- [x] MR @szha 
- [x] TREC @szha 
- [x] SUBJ @szha 
- [x] SST_1 @szha 
- [x] SST_2 @szha 
- [x] SQuAD @szha
- [x] WordSim353 @szha
- [x] RadinskyMTurk @szha
- [x] RareWords @szha
- [x] SimLex999 @szha
- [x] SimVerb3500 @szha
- [x] SemEval17Task2 @szha
- [x] BakerVerb143 @szha
- [x] YangPowersVerb130 @szha
- [x] GoogleAnalogyTestSet @szha
- [x] BiggerAnalogyTestSet @szha

**Comment by szha** [comment]
Since we already enable doctest on API documents, we can use that feature to document and check the return type of datasets and transformation functions.

**Comment by eric-haibin-lin** [comment]
Created an example in https://github.com/dmlc/gluon-nlp/pull/605.

**Comment by eric-haibin-lin** [comment]
I hope this issue can be resolved before 0.5.1 release this week. Is anyone willing to take a subset of these datasets and improve them? @leezu @sxjscience @kenjewu @fierceX @cgraywang @szhengac

**Comment by eric-haibin-lin** [comment]
Also we should add a section for all GlueXXX datasets in http://gluon-nlp.mxnet.io/master/api/modules/data.html
