### ISSUE TITLE
Host files in multiple S3 regions

### ISSUE THREAD

**Issue by leezu** [dmlc/gluon-nlp#42]
Downloading files from S3 hosted in the US can be painfully slow from Hong Kong (and likely mainland). @szha can we easily host them in a second region?
In my experience the bandwidth to Europe is good, in case that the Hong Kong region is not yet ready.

**Comment by leezu** [comment]
That works. I had some speed issues but in the end a VPN is at fault. Sorry about the noise.

**Comment by eric-haibin-lin** [comment]
Is this issue resolved?

**Comment by leezu** [comment]
I think the current S3 Accelerate approach is sufficient. AWS recently added CloudFront endpoints in Hong Kong and [mainland China](https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-cloudfront-is-now-available-in-mainland-china/). 
S3 Accelerate doesn't make use of the endpoints in mainland China though, but maybe they will in the future.

Do we have any reports of trouble downloading in China? I'll close this for now, but let's reopen once we have more evidence of the issue.

**Comment by szha** [comment]
@leezu they won't. China is a separate region entirely and there's no data exchange with the global region except on the public network.

**Comment by leezu** [comment]
Cloudflare does, so I think Cloudfront will need to do eventually as well. Cloudflare advertises this feature heavily https://www.cloudflare.com/network/china/
