### ISSUE TITLE
How to use use 2 embeddings with one acting as a backup?

### ISSUE THREAD

**Issue by Ishitori** [dmlc/gluon-nlp#423]
I load 2 embeddings into my vocab: English and Chinese. I want to use English embedding when there is a value for a particular token, and if there is no value, I would like to use Embedding value from Chinese embedding. I thought that if I add English Embedding first and Chinese Embedding next, then I will have a desired behavior. 

```
embedding_en = gluonnlp.embedding.create('fasttext', source='wiki.zh')
embedding_zh = gluonnlp.embedding.create('fasttext', source='wiki.simple')
cntr = data.count_tokens(['a', '哈'])
vocab = Vocab(cntr)
vocab.set_embedding(embedding_en, embedding_zh)
```

But actually I receive back a concatenation from both embeddings, e.g. if both embedding dimensions is 300 then I get 600 vector.  

Can I avoid the concatenation and get back only the first hit? 

At the moment, my workaround is to do embedding as a data preprocessing step, meaning I have to remove Embedding layer from the network, do token replacement not with indices, but with full-fledged vectors from embeddings using "if" and then pass vectors to the training.

**Comment by leezu** [comment]
Currently there is no out of the box support for this use-case. But it may be useful to add. With the current API, just first find all english tokens, then all chinese tokens and create a new TokenEmbedding, then assigning the correct tokens and vectors:

```
embedding_en = nlp.embedding.create('fasttext', source='wiki.zh')
embedding_zh = nlp.embedding.create('fasttext', source='wiki.simple')
cntr = nlp.data.count_tokens(['a', '哈'])
vocab = nlp.Vocab(cntr)
en_tokens = [t for t in vocab.idx_to_token if t in embedding_en]
zh_tokens = [t for t in vocab.idx_to_token if t not in en_tokens and t in embedding_zh]
embedding_en_zh = nlp.embedding.TokenEmbedding(allow_extend=True)
embedding_en_zh[en_tokens] = embedding_en[en_tokens]
embedding_en_zh[zh_tokens] = embedding_en[zh_tokens]
vocab.set_embedding(embedding_en_zh)
```

Would that work for you?

**Comment by szha** [comment]
@leezu is this possible if we reuse the subword look up interface?

**Comment by leezu** [comment]
That is another option.

**Comment by leezu** [comment]
Currently the unknown lookup can officially only be setup during initialization of a TokenEmbedding. By accessing the private member, the following should work.

```
embedding_en = gluonnlp.embedding.create('fasttext', source='wiki.zh')
embedding_zh = gluonnlp.embedding.create('fasttext', source='wiki.simple')
embedding_en._unknown_lookup = embedding_zh
```

For the current API, the following should work, but is not so nice

```
embedding_en_zh = nlp.embedding.TokenEmbedding(allow_extend=True, unknown_lookup=embedding_zh)
embedding_en_zh[en_tokens] = embedding_en[en_tokens]
```

 `vocab.set_embedding(embedding_en_zh)` will then assign an idx to the tokens that are only in embedding_zh.

**Comment by leezu** [comment]
See #429

**Comment by Ishitori** [comment]
Thank you, @leezu!

**Comment by leezu** [comment]
@Ishitori With https://github.com/dmlc/gluon-nlp/pull/459, if you have a `TokenEmbedding(..., unknown_token='<unk>', unknown_lookup=model)` and look up some unknown token that can't be computed `unknown_lookup`, it will fall back to the `'<unk>'` representation.

**Comment by Ishitori** [comment]
Great, thank you, @leezu!
