### ISSUE TITLE
[BERT] Sentence Pair Classification Followups

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#425]
- [ ] detokenization  https://github.com/dmlc/gluon-nlp/pull/409/files#r234886365
- [ ] refactor string pre-processing logic in tokenization.py by reusing gluonnlp building blocks
- [ ] memory optimization. Currently BERT takes lots of GPU memory

**Comment by szha** [comment]
There's also the conversion script and the pre-trained model for Chinese.

**Comment by eric-haibin-lin** [comment]
- [ ] Implement fine-tune example on SQUAD: https://github.com/google-research/bert/blob/master/run_squad.py

**Comment by eric-haibin-lin** [comment]
- [ ] improve sentence pair classification example speed with unpadded inputs using Bucket sampler http://gluon-nlp.mxnet.io/api/notes/data_api.html?highlight=bucketing

**Comment by eric-haibin-lin** [comment]
We also need to update the fine-tuning script to use the BERTTokenizer API introduced in https://github.com/dmlc/gluon-nlp/pull/464. Anyone wants to take that?

**Comment by Ishitori** [comment]
@eric-haibin-lin, I can take a look.

**Comment by DushyantaDhyani** [comment]
What's the status for BertDetokenizer? Can't seem to find it anywhere

**Comment by eric-haibin-lin** [comment]
Looks like i missed it in the list. Created a new issue to track that: https://github.com/dmlc/gluon-nlp/issues/1047 
The embedding script in https://github.com/dmlc/gluon-nlp/blob/v0.8.x/scripts/bert/embedding.py#L183-L197 has a function that kind of does de-tokenization, but not available through an API yet. @DushyantaDhyani would you like to contribute one?
