### ISSUE TITLE
about trainer.step() parameter

### ISSUE THREAD

**Issue by yangYu-01** [dmlc/gluon-nlp#441]
when i see the source code of step(), the needed parameter is int type, but when i run this train_transformer.py, this parameter is float(<1), i want to know is it resonable and what respective of this parameters?

**Comment by szhengac** [comment]
Though the doc says that the argument is supposed to an int variable, it can also accept a float number.

**Comment by szha** [comment]
the parameter in step() is for normalizing the aggregated gradient so that its magnitude is independent of the input batch size.
