### ISSUE TITLE
Build Gluon NLP steps

### ISSUE THREAD

**Issue by ChaiBapchya** [dmlc/gluon-nlp#443]
I wanted to add Discrete Uniform Distribution (based on randint) to the existing Candidate Sampler (currently it allows Unigram Distribution) 

Candidate Sampler is used in SG/CBOW Model for word_embeddings.

However, I was unable to find steps to build gluonnlp from source. Currently it only shows pip install in Readme.md and website.

**Comment by szhengac** [comment]
You can use pip install -e . or python setup.py develop under the gluon-nlp directory.

**Comment by ChaiBapchya** [comment]
Thanks.
