### ISSUE TITLE
Word Embeddings Training code is crashing

### ISSUE THREAD

**Issue by ifeherva** [dmlc/gluon-nlp#446]
I am trying to run the word embeddings training script but I keep getting a crash here:
https://github.com/dmlc/gluon-nlp/blob/master/scripts/word_embeddings/data.py#L205
with the wrong indexing type.
In fact idx_to_pdiscard[t] crashes as t is always a word (str) while idx_to_pdiscard is always a list of floats (defined a few lines above).

Any ideas how I could fix this quickly?

**Comment by eric-haibin-lin** [comment]
@leezu could you take a look?

**Comment by leezu** [comment]
Can you share the command you use to run the word embeddings training script?

**Comment by ifeherva** [comment]
I copied the code from here: http://gluon-nlp.mxnet.io/examples/word_embedding/word_embedding_training.html
and used the downloadable zip on the top for the missing py files.

**Comment by ifeherva** [comment]
I tried

    text8 = nlp.data.Text8()

and also my corpus:

    corpus = [[word1, word2, word3], [word4, word5, ...], ...]

Got the same error message.

**Comment by leezu** [comment]
Could it be that you are mixing code from 2 different releases? I made some changes to above script for the 0.5 release. Maybe you downloaded some code before the release and some code after? The output that you link above is created by our CI server, so the code that you see there can be run without errors. I'm not sure where exactly your error is coming from, can you post a reproducible example?

**Comment by ifeherva** [comment]
I am a very naive user:
I installed gluon-nlp with pip install gluonnlp (0.4 was installed)
Copied the code from the tutorial linked above and used the attached zip file.

**Comment by ifeherva** [comment]
Here is in the repo what I am following:
https://github.com/dmlc/gluon-nlp/blob/master/docs/examples/word_embedding/word_embedding_training.md

**Comment by leezu** [comment]
I can confirm that this file works. It generates the website you linked to above. Can you tell us the exact changes you made to this file?
Did you make sure you are using the most recent release? Try pip install --user --upgrade gluonnlp

Sorry that I can't point out the exact problem yet

**Comment by leezu** [comment]
Ok, I see you mentioned that you use the old 0.4 release. Please upgrade to 0.5 and the code will work. This is because you took the example code from the 0.5 release

**Comment by leezu** [comment]
Feel free to reopen if you have any other issues. Thanks!
