### ISSUE TITLE
get_k_closest_tokens does not return similar tokens to a word

### ISSUE THREAD

**Issue by NiallRooney** [dmlc/gluon-nlp#457]
I am following the steps in 

https://gluon-nlp.mxnet.io/examples/word_embedding/word_embedding_training.html

which returns similar results until the  following step:

example_token = "vector"
get_k_closest_tokens(vocab, embedding, 10, example_token)

which does not return similar tokens to "vector". 

closest tokens to "vector": is, in, zero, a, one, two, of, the, and, to

It appears that word vector for the example token are all zeroes and presumable all words in the vocabulary are likewise. I thought that the  intialization is based on its ngrams?

**Comment by leezu** [comment]
@NiallRooney did you follow all steps in the notebook? Actually output in the link above is automatically generated by our server running the code. Please also make sure you are using the most recent version of gluonnlp. (`pip install --user --upgrade gluonnlp` `pip3 install --user --upgrade gluonnlp`)

Feel free to reopen if the issue persists
