### ISSUE TITLE
how to implement the api in pytorch with gluon 

### ISSUE THREAD

**Issue by HuangZhanPeng** [dmlc/gluon-nlp#469]
There is two api in pytorch, one is "nn.utils.rnn.pack_padded_sequence", other is "pad_packed_sequence", I want to ask is there any api or implement to achieve the similar function of pytorch in gluon, thank you~~

**Comment by HuangZhanPeng** [comment]
@szha is there any tutorials about how to use masking to deal with? use a very small value like -np.inf?

**Comment by HuangZhanPeng** [comment]
@kenjewu got it, Thank you so much for your quick answer ! I also use this method! I just want to find out if there are other better implementations in gluon.

**Comment by szha** [comment]
@HuangZhanPeng we are looking to extend the RNN implementation in MXNet so that the variable length support can be added directly. This is tracked in https://github.com/apache/incubator-mxnet/issues/9543

Let me know if you need the issue reopened.

**Comment by HuangZhanPeng** [comment]
@szha Thank you for your response. There is no need to reopen it.
