### ISSUE TITLE
[BERT] dataset preparation script for pre-training

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#474]
Port https://github.com/google-research/bert/blob/master/create_pretraining_data.py to GluonNLP, preferably written in a way that can be used for processing large dataset

**Comment by haven-jeon** [comment]
I can help on this topic.

**Comment by eric-haibin-lin** [comment]
@haven-jeon I sent an email to `madjakarta@gmail.com` to add you to gluonnlp slack channel. Did you get that?

**Comment by haven-jeon** [comment]
I've done with RecordIO file. 
I'm not sure RecordIO is appropriate...

**Comment by haven-jeon** [comment]
I've done PR #489. 
It is basic conversion from https://github.com/google-research/bert/blob/master/create_pretraining_data.py. 
If it needs documents, Plz let me know where to write.

**Comment by eric-haibin-lin** [comment]
I documented some followup tasks I'm working on in https://github.com/dmlc/gluon-nlp/issues/521
