### ISSUE TITLE
[BERT] QA Fine-tuning Example

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#476]
Implement fine-tune example on SQUAD: https://github.com/google-research/bert/blob/master/run_squad.py

**Comment by eric-haibin-lin** [comment]
(@fierceX is leading the effort.)

**Comment by eric-haibin-lin** [comment]
follow up task listed in #502

**Comment by buechel** [comment]
@eric-haibin-lin, it looks like there is a bug between lines 461 through 479 in [here](https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/finetune_squad.py). Looks like `SQuADTransform` is called twice with identical parameters.

**Comment by eric-haibin-lin** [comment]
Hi @buechel sorry for the confusion. Both`dev_data_transform` and `dev_dataset` uses dev_data as the input, but `dev_data_transform` is processed further in a format suitable for making predictions
