### ISSUE TITLE
[BERT] Distributed Training Support

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#478]
As title.
Related issues:
https://github.com/apache/incubator-mxnet/issues/14124
[apache/incubator-mxnet#14073](https://github.com/apache/incubator-mxnet/issues/14073)
[apache/incubator-mxnet#14072](https://github.com/apache/incubator-mxnet/issues/14072)
https://github.com/apache/incubator-mxnet/issues/11061
https://github.com/apache/incubator-mxnet/issues/14125
https://github.com/apache/incubator-mxnet/issues/14126

**Comment by ymjiang** [comment]
Hi, may I know if there is any recent progress towards distributed training support? I am especially interested in training BERT and Transformer in distributed way. I did some minor modification to `train_transformer.py` script by adding `kvstore` as a param to the `gluon.Trainer`, and it worked (not sure if this is the correct way to do). But I did not try to split the dataset yet. 

Perhaps any support from official script will be better and reliable. Thanks.

**Comment by eric-haibin-lin** [comment]
Hi @ymjiang , BucketSampler is a way to create data batches of similar lengths for a dataset. https://github.com/szha/KDD18-Gluon/blob/master/05_data_pipeline/2-data-pipeline.ipynb Gluonnlp has the concept of "streams". In particular, dataset stream is an iterator which loads a dataset(typically a file) at a time. If your training data consists of multiple files, you can pass the SplitSampler to DatasetStream so that each machine iterate through a subset of files

**Comment by ymjiang** [comment]
@eric-haibin-lin I will take a look, thanks!

**Comment by eric-haibin-lin** [comment]
Added in #665
