### ISSUE TITLE
[BERT] Reproducing GLUE score on 9 tasks

### ISSUE THREAD

**Issue by haven-jeon** [dmlc/gluon-nlp#479]
Currently only provide MRPC task on https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/dataset.py 

Needs to add other tasks.
- [ ] CoLA
- [ ] SST-2
- [ ] STS-B
- [ ] QQP
- [ ] MNLI
- [ ] QNLI
- [ ] RTE
- [ ] WNLI

**Comment by kenjewu** [comment]
I want to reproduce the STS task.

**Comment by eric-haibin-lin** [comment]
@haven-jeon I created separate issues for each of these tasks and we can now track these separately as a milestone in https://github.com/dmlc/gluon-nlp/milestone/2 
I'll close this for now
