### ISSUE TITLE
some comments

### ISSUE THREAD

**Issue by mli** [dmlc/gluon-nlp#48]
I tried to read the document by assuming I have very limited knowledge about NLP and MXNet. It's not necessary to address all of them before the first lease. 

## Front-page

- [x] Add some comments into the quick example. such why we need to specify the name 'glove', what does 'glove.6B.50d.txt' mean, try to add `print(baby)`. explain what is `mx.nd.dot` (do we have an `inner` op, i feel it's more straightforward)

- [x] Probably add a link to the gluon crash course (but the crash course may contains other things not quite necessary for NLP)

## Get started

- [x] I feel we can remove this page, it's kinds of duplicated to the a quick example and the later embedding example.

### Using Pre-trained Word Embeddings

general comments,

- [x] we should explain the key concepts in details, such as "pre-trained", "word embedding", "attach", "vocab". think about we are writing a book for beginner users. or add links to refer some easy read documents 
- [x] avoid to use too much inline code blocks, may use *gluon* or just gluon instead of `gluon`. otherwise there are too many red blocks and make the doc ugly. 
- [x] use `intersphinx ` to refer mxnet.gluon.text and other mxnet apis
- [x] print as much as possible, it can save a lot of explanation words

details
 
- [x] remove 
```
import os
import sys
curr_path = os.getcwd()
sys.path.append(os.path.join(curr_path, '..', '..'))
```
it's not necessary if already installed gluonnlp

- [x] I cannot get the meaning of "let us index words, attach pre-trained word embeddings for them, " , let's explain a little bit more here. 

- [x] for In [2], split into two blocks and explain them separatly 

```
import re # move to begin?

text = " hello world \n hello nice world \n hi world \n"

tokens = filter(None, re.split(' |\n'))  # why we need filter
print(tokens)
```
  
```
counter = data.count_tokens(tokens)
```

I didn't list all details here, we can update this document according to the principals how we make these comments. 

### LM and Sentiment Analysis

- [x] documents are too short. consider explain both the model (may be briefer than our gluon book) and APIs (should in rich details) 

### Data API

- [x] add examples how to use the dataset API. since they are similar to each other, we can add an example at the begging of each section. We can apply this principal to other APIs as well. 
- [ ] add a table to list all supported datasets with columns such as  "# examples, vocab size, data size, ..."
- [ ] gluon used train, gluonvision used splits, while gluonnlp used segment. I feel we should be consistent here. 
-  [x] is it necessary to keep skip_empty? namely we have cases to keep empty? If not, we can remove this argument. If users asks for it, we can add back later. Same principal can be applied to other argument to keep the API simple
- [ ] gluon put root as the first argument, should we follow it?

### Vocab APIs

- [x] It's good we have examples to explain the APIs. But I feel they are kinds of duplicated with the embedding example. My suggestions how to distinguish them are: examples will explain the concepts and some common usages of the APIs. Users are suppose to read them to get familiar with APIs first. Then the API doc examples will concise but cover more usages, namely specifying various arguments. 

### Model API

- [x] I feel the model description is too brief. Users are hard to know what it is. I think we should explain them more
- [ ] May create a model zoo page to list all pre-traineded model, e.g. http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-40/4/model_zoo/object_detection.html

 ## Scripts

- [x] break the long command into multiple lines. 
- [x] Suggest to make the training log or a summary of the log availble. users will doubt if they are good and therefore hesitate to try them

**Comment by szha** [comment]
The comments are either stale or taken care of.
