### ISSUE TITLE
Bug in text classification script?

### ISSUE THREAD

**Issue by szhengac** [dmlc/gluon-nlp#480]
@leezu. In script `fasttext_word_ngram`, I see that the average of the word embeddings without masking out the padding tokens are used to form the hidden units. This looks like a bug as the padding tokens should not be included during averaging the representations.

**Comment by leezu** [comment]
I'm not sure about the text classification scripts. @sravanbabuiitm authored them. @sravanbabuiitm can you help clarify / fix this?

**Comment by szha** [comment]
This should have already been fixed in the previous PRs. Let me know if you need the issue reopened.
