### ISSUE TITLE
[DEV] track MXNet master nightly for development

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#488]
Recent changes depends on the latest (nightly) version of MXNet (>=1.5.0b20181228). We need to upgrade the mxnet version in gluonnlp, too.

**Comment by szha** [comment]
Agreed. The catch is we'd need to change it to depend on the latest release of mxnet before releasing GluonNLP. We can consider adopting the approach of using temporary release branches when making new releases in GluonNLP for this purpose.

**Comment by eric-haibin-lin** [comment]
There are new operators being added to mxnet for BERT which will not be on mxnet-1.4. We need to address the operator extension problem in mxnet so that ops can be added to gluonnlp

**Comment by szha** [comment]
New CI check that tracks master branch has been added.
