### ISSUE TITLE
[BERT][API] BERTVocab

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#492]
BERT has a few reserved tokens: [CLS], [SEP], [MASK], etc. Now in data processing these string literals are used in many place and it is error prone (I once wrote `[SEP` instead of `[SEP]`). Shall we introduce a BERTVocab class which inherit from the normal Vocab class with a few extra properties:
- mask_token
- sep_token
- cls_token
This way we replace all string literals with these attributes and make the code more maintainable in case we want to introduce more special tokens for pre-training. Thoughts?

**Comment by kenjewu** [comment]
This is a good idea. In addition to avoiding error of special tokens, it also simplifies the construction of the vocab for BERT (for example, set these special tokens as the default parameters of BERTVocab. Users don't need to modify it if there is no special requirement), so that the interface becomes easier to use and more elegant.

**Comment by eric-haibin-lin** [comment]
@kenjewu would you like to create a PR for it and replace the string literals in existing bert examples?

**Comment by kenjewu** [comment]
Ok! I will try to finish it.

**Comment by szha** [comment]
While it is a good idea to have a place to store the string values and indices of special tokens for a model, and vocab is definitely the place to put it, I wonder if there's a better approach to creating vocabulary classes per use case. Unlike ELMo's vocab, in which the special use of encoding value is involved (and hence a separate class for it), the vocabulary in BERT seems to follow the regular usage pattern that existing Vocab class is intended for.

This points to a drawback of current Vocab design, in which the slots of attributes/special tokens are hard coded. A more extensible way would be to allow users to register whatever special token fields are needed (except unknown token which has special fallback behavior).

@astonzhang @leezu what do you think?

**Comment by astonzhang** [comment]
That's why one of our earlier design for Vocab has a 'reserved_tokens' attribute to allow flexible extension.

**Comment by eric-haibin-lin** [comment]
Regarding a more general approach - can we extend the setattr/getattr method of Vocab class to allow registration of special tokens?

**Comment by leezu** [comment]
@eric-haibin-lin Currently not every attribute of Vocab is a special token, so overwriting the general `__setattr__` may be confusing. Maybe better to introduce something explicit? Eg either on the level of `reserved_tokens` or a separate method on the Vocab class?

**Comment by eric-haibin-lin** [comment]
@leezu Yes, adding a separate method allowing users to extend attributes sounds reasonable.

**Comment by eric-haibin-lin** [comment]
Further extension moved to https://github.com/dmlc/gluon-nlp/issues/572
