### ISSUE TITLE
embedding.from_file does not exist

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#540]
In [TokenEmbedding class API doc](http://gluon-nlp.mxnet.io/master/api/modules/embedding.html#gluonnlp.embedding.TokenEmbedding), the `gluonnlp.embedding.from_file` method is mentioned which does not exist.

Two options for the fix:
1. add a proxy method for `TokenEmbedding.from_file` in `gluonnlp.embedding` namespace.
2. update the documentation so that it refers to `gluonnlp.embedding.TokenEmbedding.from_file`.

**Comment by szha** [comment]
What's your opinion? @astonzhang @leezu

**Comment by astonzhang** [comment]
This is a typo, see PR: https://github.com/dmlc/gluon-nlp/pull/550

**Comment by szha** [comment]
Fixed in #550
