### ISSUE TITLE
[API] [BERT] Add option to return intermediate results at each layer

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#542]
Currently the BERTModel API only returns the encoding of the last layer. We should support returning intermediate encoding at each layer like ELMo. To do this, we can just add an extra argument to BERTModel to configure the model. 
https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/model/transformer.py#L480-L484

**Comment by eric-haibin-lin** [comment]
@Ishitori just curious if you have started this task? @kenjewu is working on a segmentation task and also wants this option. Just to check here to avoid duplicate work

**Comment by Ishitori** [comment]
@eric-haibin-lin, yep, I am working on that

**Comment by eric-haibin-lin** [comment]
The PR is merged. Thanks @Ishitori and @kenjewu

**Comment by nahidalam** [comment]
@eric-haibin-lin I see this PR is merged. Is there any example of how to use it?

**Comment by eric-haibin-lin** [comment]
There is not specific example just for this. You can just set the `output_attention` or `output_all_encodings` to be True when you use the `gluonnlp.model.get_bert_model` API, and additional tensors will be returned as outputs

**Comment by eric-haibin-lin** [comment]
@Ishitori I remember you were working on a tutorial to visualize the intermediate attention weights for BERT, is that already done? Any plan to contribute it back to gluonnlp?

**Comment by Ishitori** [comment]
Unfortunately, I haven't finished working on that due to lack of time. As soon as it is ready, I will contribute it back in a form of a tutorial.
