### ISSUE TITLE
FixedBucketSampler doc rendering bug

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#545]
The rendering of formula for bucket scheme is broken:
http://gluon-nlp.mxnet.io/api/modules/data.html#gluonnlp.data.FixedBucketSampler
![screen shot 2019-01-09 at 1 23 46 pm](https://user-images.githubusercontent.com/5545640/50929338-d90cb900-1411-11e9-8391-9028449c30fb.png)

**Comment by anuragsarkar97** [comment]
#583

**Comment by eric-haibin-lin** [comment]
@anuragsarkar97 thanks for your contribution!

**Comment by anuragsarkar97** [comment]
No problem at all 👍
