### ISSUE TITLE
BERT Download link broken

### ISSUE THREAD

**Issue by sravanbabuiitm** [dmlc/gluon-nlp#552]
In the documentation : http://gluon-nlp.mxnet.io/examples/sentence_embedding/bert.html
The link for download on this line under 

Preparation:
"To run this tutorial locally, please install gluonnlp and click the download button at the top to get all related code."

seems to be broken.

I had to copy link address at the top to download.
! wget http://gluon-nlp.mxnet.io/_downloads/sentence_embedding.zip

Can this be fixed, given the milestone BERT is, and how many ppl might be using this tutorial

**Comment by szha** [comment]
@eric-haibin-lin seems that the change in #440 caused some confusion.

**Comment by eric-haibin-lin** [comment]
Thanks for reporting. I created https://github.com/dmlc/gluon-nlp/pull/554

**Comment by szha** [comment]
The redundant link was removed in #554
