### ISSUE TITLE
CI seems to be a little unstable

### ISSUE THREAD

**Issue by kenjewu** [dmlc/gluon-nlp#559]
The py2 detection in CI seems to be unstable, and several times in the detection of #526, py2 unexpectedly failed. But after using empty commit to re-trigger it, py2 passed. 

http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-526/18/pipeline
http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-526/19/pipeline

The same problem was occasionally encountered in previous PR.

**Comment by szha** [comment]
I'm looking into it.

**Comment by szha** [comment]
Since the problem is not occurring, I will track the rest of the progress on speeding up the CI and making it robust in #302
