### ISSUE TITLE
A typo in word embedding tutorial

### ISSUE THREAD

**Issue by junrushao1994** [dmlc/gluon-nlp#560]
In our word embedding [tutorial](https://gluon-nlp.mxnet.io/model_zoo/word_embeddings/index.html), it looks like `--ngram-buckts` should be `--ngram-buckets`.

**Comment by junrushao1994** [comment]
And `--max-vocab-size` in `run_all.sh` should be `--analogy-max-vocab-size`. Do we have CI run on this tutorial?

**Comment by szha** [comment]
@junrushao1994 thanks for finding them. @leezu would be interested. We run the python scripts but not the scripts or the command lines.
