### ISSUE TITLE
Add other BERT models

### ISSUE THREAD

**Issue by xiejianhe** [dmlc/gluon-nlp#569]
Please add other BERT models, like "BERT-Base, Chinese", "BERT-Base, Multilingual Cased (New, recommended)".

**Comment by eric-haibin-lin** [comment]
Hi @xiejianhe these two are available on gluonnlp master branch http://gluon-nlp.mxnet.io/master/model_zoo/bert/index.html and you install the master branch following the instructions here http://gluon-nlp.mxnet.io/master/install.html#

**Comment by szha** [comment]
0.5.1 release will make them available. Some open tasks before release are tracked in #570

**Comment by xiejianhe** [comment]
@eric-haibin-lin Thank you!

**Comment by szha** [comment]
Tracked in #570
