### ISSUE TITLE
0.6 release tasks

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#570]
Given recent development with BERT models, @szha and I propose that we release 0.6.0 when the following items are ready:

PRs:
- [x] #505
- [x] #493 by @fierceX 
- [x] #481 by @haven-jeon 

Issues:
- [x] #308 
- [x] #364 
- [ ] #374
- [ ] #405 
- [x] https://github.com/dmlc/gluon-nlp/issues/491

**Comment by eric-haibin-lin** [comment]
WIP Draft release note in https://hackmd.io/KNRvun3jTCW6q8Pg1iISeQ?both

**Comment by eric-haibin-lin** [comment]
I've updated the release note with credit and split PRs into sections
@dmlc/gluon-nlp-reviewers

**Comment by szha** [comment]
+1

**Comment by szha** [comment]
0.6 has been released.
