### ISSUE TITLE
[Vocab] Support special token registration 

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#572]
per discussion in https://github.com/dmlc/gluon-nlp/issues/492#issuecomment-451769526
We want an extensible way which allows users to register whatever special token fields are needed (except unknown token which has special fallback behavior).

For example:
```
>>> vocab = nlp.Vocab(...)
>>> vocab.register_special_token('mask', '[MASK]')
>>> vocab.mask
'[MASK]'
>>> vocab['mask']
'[MASK]'
```

**Comment by szha** [comment]
Registering new special token after construction would likely complicate many parts, such as shuffling attached embeddings. We should allow special tokens to be added as attributes in the constructor as a first step.
