### ISSUE TITLE
[word2vec] Add word2vec binary load function

### ISSUE THREAD

**Issue by imgarylai** [dmlc/gluon-nlp#577]
I'm willing to add this feature to gluon-nlp. 

Our lab is using gensim to load word2vec binary file and we want to get rid of it. @szha and I have discussed with issue before. This would be great that gluon-nlp can have an interface to load our own pre-trained fastText binary. 

@szha @leezu, please let me know how can I help you guys for this.

**Comment by szha** [comment]
Hi @imgarylai. Thanks for offering to help! For fastText format, there's a `load_fasttext_format` method in the [FasttextEmbeddingModel](http://gluon-nlp.mxnet.io/api/modules/model.train.html#gluonnlp.model.train.FasttextEmbeddingModel) class that can be used without gensim.

**Comment by szha** [comment]
Alternatively, the word2vec format is still missing. Would that be something you're interested in too?

**Comment by imgarylai** [comment]
Yes. I have changed the title. 😝

**Comment by leezu** [comment]
Thanks @imgarylai 

I guess the best way forward would be to just specialize / overwrite the `from_file` for the `Word2Vec` class https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/embedding/token_embedding.py#L961 

(For fastText this was instead added in the `model.train.embedding` API as the binary format does not contain the "final" vectors but rather the vectors for all words / ngrams that must still be combined. But this does not apply in the W2V case.)

**Comment by szha** [comment]
@imgarylai Word2Vec class was written in the way that requires source so that automatic downloading is easier. You can think of the `from_file`/`load_w2v_binary` method as another constructor independent of the source abstraction.

**Comment by imgarylai** [comment]
Move to #620
