### ISSUE TITLE
Word language model has problematic performance

### ISSUE THREAD

**Issue by szhengac** [dmlc/gluon-nlp#580]
I ran the `word_language_model.py` on the current master branch with following cmd:

`python word_language_model.py --gpu 0 --tied --ntasgd --lr_update_interval 50 --lr_update_factor 0.5 --save awd_lstm_lm_1150_wikitext-2`

The performance are significantly worse than the one shown in the log. The results are shown as follows. It seems the training is not correct.

[Epoch 326 Batch 200/372] current loss 6.21, ppl 499.30, throughput 234.71 samples/s, lr 0.43
[Epoch 326] throughput 16464.32 samples/s
[Epoch 326] time cost 134.05s, valid loss 6.96, valid ppl 1055.76，lr 0.47
[Epoch 327 Batch 200/372] current loss 6.21, ppl 498.77, throughput 239.18 samples/s, lr 0.45
[Epoch 327] throughput 16279.53 samples/s
[Epoch 327] time cost 135.56s, valid loss 6.96, valid ppl 1057.93，lr 0.47
[Epoch 328 Batch 200/372] current loss 6.21, ppl 497.68, throughput 237.90 samples/s, lr 0.40
[Epoch 328] throughput 16070.73 samples/s
[Epoch 328] time cost 137.13s, valid loss 6.97, valid ppl 1060.08，lr 0.47
[Epoch 329 Batch 200/372] current loss 6.22, ppl 500.59, throughput 241.20 samples/s, lr 0.20
[Epoch 329] throughput 16449.73 samples/s
[Epoch 329] time cost 134.20s, valid loss 6.97, valid ppl 1062.16，lr 0.47
[Epoch 330 Batch 200/372] current loss 6.22, ppl 500.81, throughput 245.66 samples/s, lr 0.50
[Epoch 330] throughput 16533.50 samples/s
[Epoch 330] time cost 133.68s, valid loss 6.97, valid ppl 1064.21，lr 0.47
[Epoch 331 Batch 200/372] current loss 6.22, ppl 501.55, throughput 247.52 samples/s, lr 0.49
[Epoch 331] throughput 16659.26 samples/s
[Epoch 331] time cost 132.51s, valid loss 6.97, valid ppl 1066.25，lr 0.47
[Epoch 332 Batch 200/372] current loss 6.21, ppl 496.57, throughput 251.29 samples/s, lr 0.45
[Epoch 332] throughput 16314.63 samples/s
[Epoch 332] time cost 135.29s, valid loss 6.97, valid ppl 1068.32，lr 0.47
[Epoch 333 Batch 200/372] current loss 6.22, ppl 500.40, throughput 243.31 samples/s, lr 0.48
[Epoch 333] throughput 16411.81 samples/s
[Epoch 333] time cost 134.50s, valid loss 6.98, valid ppl 1070.33，lr 0.47
[Epoch 334 Batch 200/372] current loss 6.21, ppl 498.75, throughput 242.56 samples/s, lr 0.48
[Epoch 334] throughput 16247.07 samples/s
[Epoch 334] time cost 135.67s, valid loss 6.98, valid ppl 1072.37，lr 0.47
[Epoch 335 Batch 200/372] current loss 6.21, ppl 498.41, throughput 235.91 samples/s, lr 0.42
[Epoch 335] throughput 16232.91 samples/s
[Epoch 335] time cost 135.87s, valid loss 6.98, valid ppl 1074.41，lr 0.47
[Epoch 336 Batch 200/372] current loss 6.22, ppl 500.23, throughput 234.02 samples/s, lr 0.38
[Epoch 336] throughput 16084.55 samples/s
[Epoch 336] time cost 137.03s, valid loss 6.98, valid ppl 1076.43，lr 0.47
[Epoch 337 Batch 200/372] current loss 6.22, ppl 502.17, throughput 234.21 samples/s, lr 0.21
[Epoch 337] throughput 15950.04 samples/s
[Epoch 337] time cost 138.05s, valid loss 6.98, valid ppl 1078.42，lr 0.47
[Epoch 338 Batch 200/372] current loss 6.21, ppl 496.63, throughput 234.94 samples/s, lr 0.46
[Epoch 338] throughput 15970.70 samples/s
[Epoch 338] time cost 137.94s, valid loss 6.99, valid ppl 1080.42，lr 0.47
[Epoch 339 Batch 200/372] current loss 6.21, ppl 497.47, throughput 247.33 samples/s, lr 0.44
[Epoch 339] throughput 16786.18 samples/s
[Epoch 339] time cost 131.77s, valid loss 6.99, valid ppl 1082.41，lr 0.47
[Epoch 340 Batch 200/372] current loss 6.21, ppl 498.09, throughput 240.05 samples/s, lr 0.44

**Comment by cgraywang** [comment]
@szhengac please refer to my comments in https://github.com/dmlc/gluon-nlp/issues/364 , thanks.

**Comment by cgraywang** [comment]
Based on the offline discussion, the script works properly now.
