### ISSUE TITLE
[Transformer] Avoid adding dropout layers if dropout = 0

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#596]
I noticed that the Transformer blocks add dropout layers even if dropout is set to 0 https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/model/transformer.py#L109, which is bad for inference due to extra copies. We should avoid adding the `Dropout` layer if self._dropout == 0. 
cc @TaoLv

**Comment by TaoLv** [comment]
Filed a PR here: https://github.com/dmlc/gluon-nlp/pull/597

**Comment by eric-haibin-lin** [comment]
Fixed now
