### ISSUE TITLE
STORIES corpus

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#598]
Here's a cleaned-up corpus from Trinh et. al., consisting of stories
https://console.cloud.google.com/storage/browser/commonsense-reasoning/reproduce/stories_corpus?pli=1
https://arxiv.org/abs/1806.02847

Given the effectiveness of large and clean corpora with deep transformer models, shown in BERT and GPT-2, this might be useful to others. Should we offer the automatic download of this corpus in GluonNLP?

**Comment by eric-haibin-lin** [comment]
+1

**Comment by szha** [comment]
Tracked in the above issue.
