### ISSUE TITLE
Flaky test in CI 

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#608]
Documentation change in https://github.com/dmlc/gluon-nlp/pull/605 failed  the transformer script test. http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-605/4/pipeline 

Import mxnet failed

**Comment by eric-haibin-lin** [comment]
again in http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/master/375/pipeline

**Comment by imgarylai** [comment]
It happens here: http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-620/15/pipeline

**Comment by szha** [comment]
CI has been fully refactored and things seem to be stable so far.
