### ISSUE TITLE
gluon-nlp 0.6 release blog post draft 

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#623]
Hi everyone,

As we are close to finishing up tasks for the release #570, I am writing up a blog draft to introduce gluon-nlp 0.6 release. Please help review and comment on the blog post. Thanks!

https://medium.com/p/6a489bdd3340

@dmlc/gluon-nlp-team

Best,
Haibin

**Comment by szha** [comment]
@dmlc/gluon-nlp-team

**Comment by mli** [comment]
Suggest to emphasize "pre-training" scripts. e.g. it's the first repo to reproduce the results, talk about performance including speed. Also "The Sesame Street gang is taking over the world of Natural Language Processing (NLP)" is not professionaly, not everyone thinks so.

**Comment by szha** [comment]
Blog is posted.
