### ISSUE TITLE
About the BERTVocab.cls_token and BERTVocab.CLS_TOKEN

### ISSUE THREAD

**Issue by zyds** [dmlc/gluon-nlp#652]
Hi, when I try to use the BERTVocab, I found a problem.

The code is :

-----------------------------------------------------------------------------------
model, vocab = nlp.model.get_bert_model('bert_12_768_12', dataset_name='wiki_cn_cased', pretrained=True, ctx=mx.cpu(0), use_pooler=False, use_decoder=False, use_classifier=False)
print(vocab)
print("vocab.CLS_TOKEN:", vocab.CLS_TOKEN)
print("vocab.cls_token:", vocab.cls_token)
-------------------------------------------------------------------------------------

But the output is:

-------------------------------------------------------------------------------------
Vocab(size=21128, unk="[UNK]", reserved="['[PAD]', '[CLS]', '[SEP]', '[MASK]']")
vocab.CLS_TOKEN: [CLS]
vocab.cls_token: None
-------------------------------------------------------------------------------------
The environment is python3.5.2, mxnet-cu90==1.4.0, gluonnlp==0.6.0.

**Comment by eric-haibin-lin** [comment]
@kenjewu could you take a look at this?

**Comment by kenjewu** [comment]
Ok, I will check it later. If there is an error, I will open a new PR to fix it.

**Comment by shenfei** [comment]
+1 Encounter the same problem.

`cls_token` is missing in `wiki_cn_cased` vocabulary.

Here is a reproducible example:

```python
In [1]: from mxnet.gluon.utils import check_sha1

In [2]: from gluonnlp.data.utils import _vocab_sha1

In [3]: check_sha1('wiki_cn_cased-a1e06f8e.vocab', _vocab_sha1['wiki_cn_cased'])
Out[3]: True

In [4]: import json

In [5]: with open('wiki_cn_cased-a1e06f8e.vocab', 'r') as f:
   ...:     json_str = f.read()
   ...:

In [6]: vocab_dict = json.loads(json_str)

In [7]: print(vocab_dict.keys())
dict_keys(['idx_to_token', 'token_to_idx', 'reserved_tokens', 'unknown_token', 'padding_token', 'bos_token', 'eos_token'])

In [8]: print(vocab_dict.get('cls_token'))
None
```

mxnet 1.4.0, gluonnlp 0.6.0, python 3.6.7

**Comment by kenjewu** [comment]
I did some checks and found that this problem only occurs when using the `wiki_cn_cased data`.  After checking the dictionary corresponding to `wiki_cn_cased`, I found that there is no `CLS` keyword in the json file of this dictionary.  
```python
dict_keys(['idx_to_token', 'token_to_idx', 'reserved_tokens', 'unknown_token', 'padding_token', 'bos_token', 'eos_token'])
```
 I think this should be a missing conversion.

**Comment by kenjewu** [comment]
I did some checks and found that this problem only occurs when using the `wiki_cn_cased data`.  After checking the dictionary corresponding to `wiki_cn_cased`, I found that there is no `CLS` keyword in the json file of this dictionary.  
```python
dict_keys(['idx_to_token', 'token_to_idx', 'reserved_tokens', 'unknown_token', 'padding_token', 'bos_token', 'eos_token'])
```
 I think this should be a missing conversion.

**Comment by kenjewu** [comment]
I will convert these two dictionaries.

**Comment by kenjewu** [comment]
it has been fixed.
