### ISSUE TITLE
Find a Bug in pretrain script of bert

### ISSUE THREAD

**Issue by Gpwner** [dmlc/gluon-nlp#660]
https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/run_pretraining.py

line 296 and 297,throw a exception：

```
Traceback (most recent call last):
  File "/home/xzc/gluon-nlp/scripts/bert/run_pretraining.py", line 477, in <module>
    evaluate(data_eval, model, nsp_loss, mlm_loss, len(vocabulary), ctx)
  File "/home/xzc/gluon-nlp/scripts/bert/run_pretraining.py", line 297, in evaluate
    mlm_metric.reset_running()
AttributeError: 'MaskedAccuracy' object has no attribute 'reset_running'
```

**Comment by szhengac** [comment]
This feature was added in #503, Jan 2, 2019. I think your version of gluonnlp may be old. Please try the latest version: pip install --pre gluonnlp.

**Comment by szhengac** [comment]
@eric-haibin-lin I just checked the class `MaskedAccuracy`, there is no function called `reset_running`.

**Comment by eric-haibin-lin** [comment]
Sorry it should be reset_local instead. I'll make a PR with the fix
