### ISSUE TITLE
[BERT] LAMB optimizer

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#677]
Reference: https://arxiv.org/abs/1904.00962

Author claimed that with the help of LAMB optimizer, super large batch size can be used to improve the scalability of BERT models, so that a BERT model can be trained in a little over 1 hour. However, given that only squad finetuning is included in the experiment, it's unclear whether the trained BERT model is actually of the same quality as the original BERT, especially since we found squad finetuning is the easiest task to match performance when reproducing BERT pre-training. Once we have the LAMB optimizer implementation, it would be interesting to replicate the experiment in LAMB paper and validate it on other finetuning tasks in GLUE.

**Comment by kenjewu** [comment]
Is anyone doing this work now?

**Comment by szha** [comment]
not yet

**Comment by eric-haibin-lin** [comment]
@kenjewu what about porting transformer-xl to gluonnlp first, then implement and validate lamb optimizer following https://medium.com/south-park-commons/scaling-transformer-xl-to-128-gpus-85849508ec35  ?
