### ISSUE TITLE
Potential regression in MXNet nightly

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#706]
HybridBeamSearchSampler can no longer correctly infer shape:

http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-cpu-unittest/detail/PR-705/7/pipeline/
in PR https://github.com/dmlc/gluon-nlp/pull/705 

@junrushao1994 do you have any idea?

**Comment by junrushao1994** [comment]
May be related to the recent dynamic shape PR which removes shape inference on control flow operators. Will look into it!
