### ISSUE TITLE
Distributed Sampler Support for Multi-GPU Training with Horovod

### ISSUE THREAD

**Issue by rich-junwang** [dmlc/gluon-nlp#713]
The current distributed training with Horovod only supports file split if my understanding is correct (https://github.com/horovod/horovod/blob/master/examples/mxnet_mnist.py). Could we have a distributed sampler that can distribute samples to all GPUs if we read data from a single file?

**Comment by eric-haibin-lin** [comment]
@szhengac Maybe we can make a small adaption in http://gluon-nlp.mxnet.io/master/api/modules/data.html?highlight=shardeddataloader#gluonnlp.data.ShardedDataLoader and return the result for a specific shard instead?

**Comment by eric-haibin-lin** [comment]
We can now use the Dataset.shard API in mxnet nightly: https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/data/dataset.py#L67-L96
