### ISSUE TITLE
python2 end of life (will announce deprecation in 0.7)

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#721]
@dmlc/gluon-nlp-team 
Python2 will stop its support on January 1, 2020. We need to discuss a timeline to drop python2 support for gluon-nlp, too. 

https://www.python.org/dev/peps/pep-0373/

There's also a discussion thread to drop py2 for mxnet https://lists.apache.org/thread.html/f8440615095c5472d1b16c554fca0fe5bad3fb8b20feaceba39ca694@%3Cdev.mxnet.apache.org%3E

**Comment by szha** [comment]
Some specific items to think about:
- when shall we start adding API that only supports py3? (I'd suggest immediately)
- when shall we remove support for py2 altogether? (I'd suggest in at least two more releases)

**Comment by leezu** [comment]
Let's announce the deprecation of Py2 with 0.7 release and remove the support with the 0.8 release.

**Comment by sxjscience** [comment]
+1 for deprecating py2 in 0.7

**Comment by szha** [comment]
Looks like the consensus is to announce deprecation of python2 support in 0.7.

**Comment by leezu** [comment]
I disabled the Python 2 jobs on our CI for pull-requests and the master branch.

**Comment by leezu** [comment]
@szha could you update the repository rules ("expected checks") on the Github side?

**Comment by szha** [comment]
updated. the python2 checks are no longer required.
