### ISSUE TITLE
gluonnlp._constant not using unicode for python2

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#722]
The pre-defined constants with py2 are encoded in ascii instead of unicode. This causes inconsistency in nlp.vocab.Vocab, where some tokens may be in unicode, and some reserved tokens are in ascii. 

This may cause issue if users pre-process data with hard-coded string literals that is inconsistent with what's stored in Vocab.

**Comment by leezu** [comment]
The same applies to the defaults in `token_embedding.py`

**Comment by szha** [comment]
we're opting for py2 deprecation #721
