### ISSUE TITLE
PrefetcherIter with worker_type='process' may hang

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#724]
I noticed that using PrefetcherIter with worker_type='process' may leave the prefetching process hang. Specifically, if I do 
```
kill $PARENT_PID
```
I will observe that the parent process exits, and that child process still runs. And the child process runs till https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/data/stream.py#L265-L271 and block there because the parent never calls `__next__`. 

I'm a bit confused because the process is already marked as daemon=True, but it does not exit.

**Comment by eric-haibin-lin** [comment]
@leezu have u seen this before?

**Comment by leezu** [comment]
@eric-haibin-lin did you confirm the child processes exit correctly if you don't send TERM to the parent process but exit it via Python?

**Comment by leezu** [comment]
Maybe https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/data/stream.py#L265-L271 catches the KeyboardInterrupt exception?

**Comment by eric-haibin-lin** [comment]
Yes if I press control+c it exits successfully

**Comment by eric-haibin-lin** [comment]
I was experimenting with `SIGTERM ` because that's the way openmpi kills a worker, which might be an issue if we use horovod for distributed training
