### ISSUE TITLE
CI reports linkcheck as passing for pull-requests even though it fails

### ISSUE THREAD

**Issue by leezu** [dmlc/gluon-nlp#751]
@szha There is some bug in the CI setup for pull-requests. Even though the
linkcheck consistently failed for all pull-requests after #566, the CI did not
recognize the failure and reported the test as passing. Only on the master
branch, the CI correctly reports the test as failing.

See for example the log for #732:
- The pipeline checking the links is reported as passing
  http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-732/32/pipeline/85
- However, looking at the detailed log files,
  http://ci.mxnet.io/blue/rest/organizations/jenkins/pipelines/GluonNLP-py3-master-gpu-doc/branches/PR-732/runs/32/nodes/85/steps/106/log/?start=0
  we see that the recipe for target linkcheck failed and reported Error 1 (last few lines)

**Comment by leezu** [comment]
This may be fixed by removing https://github.com/dmlc/gluon-nlp/blob/1e50a6606c5215e0dc28d016bb5f57bd668f47af/ci/jenkins/build_steps.groovy#L120

This is tentatively done in #752.

@szha What was the reason to add
https://github.com/dmlc/gluon-nlp/blob/1e50a6606c5215e0dc28d016bb5f57bd668f47af/ci/jenkins/build_steps.groovy#L120

**Comment by szha** [comment]
Some external websites were down so this was added as a temporary measure. it shouldn't be needed anymore.
