### ISSUE TITLE
Missing wiki_cn Bert vocab artifacts on S3

### ISSUE THREAD

**Issue by leezu** [dmlc/gluon-nlp#753]
@szha, following https://github.com/dmlc/gluon-nlp/pull/655 please copy 

`aws s3 cp s3://apache-mxnet/gluon/dataset/vocab/wiki_cn_cased-ddebd8f3.zip s3://apache-mxnet/gluon/dataset/vocab/wiki_cn-ddebd8f3.zip`

Both are required, as `wiki_cn` is an alias of `wiki_cn_cased`.

This bug must not be closed before tests are added that would have caught this error.

**Comment by leezu** [comment]
@kenjewu FYI

**Comment by szha** [comment]
done
