### ISSUE TITLE
Incorrect TOC in the website sidebar for tutorials

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#760]
"process data", "loading pretrained elmo data", "putting everything together" should not appear in the sidebar.

<img width="886" alt="Screen Shot 2019-06-09 at 2 01 12 PM" src="https://user-images.githubusercontent.com/5545640/59164236-30957a80-8abf-11e9-90b3-01151821f0d8.png">

**Comment by szha** [comment]
This is already fixed in http://gluon-nlp.mxnet.io/master/index.html

**Comment by eric-haibin-lin** [comment]
Back to normal when I checked the website today again. Not sure why it happened. Let's reopen if it appears
