### ISSUE TITLE
Port XLNet to gluonnlp 

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#787]
https://github.com/zihangdai/xlnet
https://arxiv.org/abs/1906.08237

**Comment by thomelane** [comment]
Aside from the great results, I'd be be interested to see if the 'segments' idea from TransformerXL helps out on long range tasks like document segmentation.

**Comment by sxjscience** [comment]
@ThomasDelteil Yes, I'll try to reproduce the TransformerXL in GluonNLP. See https://github.com/dmlc/gluon-nlp/issues/797
