### ISSUE TITLE
simverb3500 link broken

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#788]
## Description
http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-783/3/pipeline#step-64-log-1246

## What have you tried to solve it?

We will skip its test for now which needs to be added back.

**Comment by eric-haibin-lin** [comment]
is this fixed or skipped?

**Comment by szha** [comment]
skipped. the functionality is broken.
