### ISSUE TITLE
ATIS/SNIPS datasets and GLUE datasets don't appear in the website API doc 

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#831]
http://gluon-nlp.mxnet.io/api/modules/data.html

does not show the details of ATISDataset/SNIPSDataset and GlueCoLA, GlueSST2, GlueSTSB, GlueQQP, GlueRTE, GlueMNLI, GlueQNLI, GlueWNLI

**Comment by eric-haibin-lin** [comment]
the issue persists in http://gluon-nlp.mxnet.io/api/modules/data.html

**Comment by kevicao** [comment]
I got the following error

ImportError                               Traceback (most recent call last)
<ipython-input-2-0f4f2a9f6654> in <module>
----> 1 from gluonnlp.data import ATISDataset

ImportError: cannot import name 'ATISDataset'

**Comment by szha** [comment]
Thanks for the reminder. I need to add this to the 0.7 branch and sync the doc.

**Comment by eric-haibin-lin** [comment]
The commit is in the branch. Maybe we just need to rebuild the website

**Comment by szha** [comment]
Updated and verified that the docs are there now.
