### ISSUE TITLE
How can i load pretained biobert  with  BertEmbedding,

### ISSUE THREAD

**Issue by cpmss521** [dmlc/gluon-nlp#843]
i get  a  `ValueError` when  use `BertEmbedding` ,
 `bert_embedding = BertEmbedding(model='bert_24_1024_16', dataset_name="biobert_v1.1_pmc_cased")`,
`ValueError: Vocabulary for biobert_v1.1_pmc_cased is not available.` this  `BertEmbedding` is not support pretained  biobert??

**Comment by szha** [comment]
@cpmss521 'biobert_v1.1' only has the 'pubmed_cased' BERT base model version available. This should work: `bert_embedding = BertEmbedding(model='bert_12_768_12', dataset_name="biobert_v1.1_pubmed_cased")`

**Comment by cpmss521** [comment]
thanks a lot ,but  it didn;t work :bert_embedding = BertEmbedding(model='bert_12_768_12', dataset_name="biobert_v1.1_pubmed_cased")  and raised the same error "ValueError: Vocabulary for biobert_v1.1_pubmed_cased is not available."  but  i get some information  about pre-trained BERT models  in [here](http://gluon-nlp.mxnet.io/model_zoo/bert/index.html),, i don't know  what's wrong ?

**Comment by eric-haibin-lin** [comment]
@cpmss521 what's your gluon-nlp version? Does gluonnlp 0.7.1 not work?

**Comment by cpmss521** [comment]
according to description [here](https://github.com/imgarylai/bert-embedding#install) :`pip install bert-embedding`,`pip install mxnet-cu92`,and then i get gluonnlp==0.6.0, @eric-haibin-lin ,

**Comment by szha** [comment]
@imgarylai would you mind updating the dependency of bert-embedding to gluonnlp>=0.6.0?

**Comment by imgarylai** [comment]
The `bert-embedding` has been updated and asked for `gluonnlp >= 0.6.0` as a dependency.

https://github.com/imgarylai/bert-embedding/blob/910dc59ce123fc3a72b9428d7e9cc4b693844e04/setup.py#L140

Try to run `pip install gluonnlp==0.7.1` after install bert-embedding?

**Comment by szha** [comment]
This has been resolved in the downstream.
