### ISSUE TITLE
Missing error log from CI

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#881]
The notebook tests in some cases don't report the error log:
http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-877/9/pipeline
Not sure if it's transient or consistent across runs

**Comment by eric-haibin-lin** [comment]
Triggered it again and the log is still missing. cc @leezu

**Comment by leezu** [comment]
Triggering again as the logs from your last run are already deleted (12 hour timeout)

**Comment by leezu** [comment]
I found some job status reports that indicate that your jobs were timing out. Are you sure #877 does not introduce any regression that prevents the transformer example from running? The Cloudwath log does not contain any output after minute 2 (and until it is killed at minute 30)

**Comment by leezu** [comment]
I'll open a PR to make sure the stderr output is also sent to Cloudwatch. Currently we can't access stderr output as it is only logged to a file but that file is never uploaded to S3 due to the job timeout.

**Comment by eric-haibin-lin** [comment]
Yes I also find that the job exceeded 30 mins. There was indeed a bug that causes the translation regression.
