### ISSUE TITLE
Self-attentive Sentence Embedding Tutorial Undeclared Dependency (sklearn)

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#886]
## Description
self-attentive sentence embedding tutorial is using sklearn for accuracy and f1. As we didn't take sklearn as a dependency, we should migrate those usage to the accuracy/f1 in mxnet and drop the dependency in docker

**Comment by avinashsai** [comment]
@szha 
I have the code ready with sklearn accuracy metric changed to mxnet accuracy metric. However, mxnet F1 currently supports binary classification. However, this tutorial is a multi-class classification and hence will not be able to use mxnet F1 metric. Should I submit PR only with accuracy changed or leave it as it is??

**Comment by leezu** [comment]
@avinashsai you may be interested in the mxnet metrics improvements for mxnet 2: https://github.com/apache/incubator-mxnet/pull/18083

If you have the code ready, it's good to submit the part that can be supported by mxnet metric
