### ISSUE TITLE
Setup fails because of UnicodeDecodeError

### ISSUE THREAD

**Issue by Dobatymo** [dmlc/gluon-nlp#90]
This line `readme = open('README.rst').read()` in setup.py can cause an decoding error on windows. For example my system uses cp950 as default code page.

please specify an explicit encoding (I guess utf-8 would be correct)
```
from io import open # for python2.7 compatibility
readme = open('README.rst', encoding="utf-8").read()
```

**Comment by szha** [comment]
Fixed. Also updated pip with version 0.2.0.post0.
