### ISSUE TITLE
Environment variable for configuring the default downloading location

### ISSUE THREAD

**Issue by sxjscience** [dmlc/gluon-nlp#93]
Currently all models/datasets will be downloaded to `~/.mxnet/...` by default. We should add an environment variable to configure the constant. Sometimes the user may not have enough space under `~` and will need to download the dataset to another location.

**Comment by leezu** [comment]
@lixin4ever you can usually pass the `root='/some/path/` parameter to functions that download files (ie datasets/models). The change proposed by @sxjscience needs some (trivial) changes in the code, but no-one has done them yet. If you would like to contribute it, please let us know and we can provide guidance.

**Comment by lixin4ever** [comment]
@leezu I am happy to contribute to this project. How to start? Is there any guidance or documentation online?

**Comment by szha** [comment]
@leezu We can start using `MXNET_HOME` with this package first and propagate the change back to mxnet later on.

**Comment by sxjscience** [comment]
Thanks @lixin4ever for contributing. This has been solved by https://github.com/dmlc/gluon-nlp/pull/106 .
