### ISSUE TITLE
Korean BERT pre-trained

### ISSUE THREAD

**Issue by haven-jeon** [dmlc/gluon-nlp#939]
## Description
- Korean BERT pre-trained cased (KoBERT)

## References
- https://github.com/SKTBrain/KoBERT

**Comment by eric-haibin-lin** [comment]
Nice! Are you porting it back to gluonnlp's model zoo?

**Comment by haven-jeon** [comment]
> Nice! Are you porting it back to gluonnlp's model zoo?

Sure.

**Comment by szha** [comment]
we plan to make a release around Oct 20th in preparation for our EMNLP tutorial (Nov 3rd). @haven-jeon would you be able to include this feature?

**Comment by muhyun** [comment]
> > Nice! Are you porting it back to gluonnlp's model zoo?
> 
> Sure.

Heewon-nim, I am a data scientist in AWS based in Korea and I'd like to have a talk on Korean BERT pre-trained model implementation into GluonNLP. If you are interested in working together, please reply. :)

**Comment by haven-jeon** [comment]
> we plan to make a release around Oct 20th in preparation for our EMNLP tutorial (Nov 3rd). @haven-jeon would you be able to include this feature?

Sorry for missing this message. I can make patch until end of Nov.

**Comment by haven-jeon** [comment]
> > > Nice! Are you porting it back to gluonnlp's model zoo?
> > 
> > 
> > Sure.
> 
> Heewon-nim, I am a data scientist in AWS based in Korea and I'd like to have a talk on Korean BERT pre-trained model implementation into GluonNLP. If you are interested in working together, please reply. :)

Thanks for your suggestions. 
It will be happy work together.

**Comment by jamiekang** [comment]
Recent official ALBERT code:
https://github.com/google-research/google-research/tree/master/albert

**Comment by haven-jeon** [comment]
Hi! @eric-haibin-lin  I currently working on porting KoBERT to GluonNLP. 
Could you upload to model zoo these binary?

model
https://kobert.blob.core.windows.net/models/kobert/mxnet/bert_12_768_12_kobert_news_wiki_ko_cased-ccf0593e.params
sha1sum : ccf0593e03b91b73be90c191d885446df935eb64

vocab(tokenizer)
https://kobert.blob.core.windows.net/models/kobert/tokenizer/kobert_news_wiki_ko_cased-f86b1a83.spiece.zip
sha1sum : f86b1a8355819ba5ab55e7ea4a4ec30fdb5b084f

**Comment by leezu** [comment]
@szha can help.

**Comment by szha** [comment]
done. sorry for the delay.

**Comment by haven-jeon** [comment]
Thanks @szha, I will PR.
