### ISSUE TITLE
Chinese Roberta conversion

### ISSUE THREAD

**Issue by kenjewu** [dmlc/gluon-nlp#965]
## Description
Provides Roberta parameters pre-trained by large-scale Chinese corpus.
I plan to convert it from https://github.com/brightmart/roberta_zh
## References
- https://github.com/brightmart/roberta_zh

**Comment by szha** [comment]
Thanks @kenjewu . We are hoping to create a release in about 10 days in preparation for EMNLP. Do you think it would make the next release?

**Comment by kenjewu** [comment]
> Thanks @kenjewu . We are hoping to create a release in about 10 days in preparation for EMNLP. Do you think it would make the next release?

I mainly complete related conversion and testing work. I think it can be done before this deadline.

**Comment by kenjewu** [comment]
Due to work changes, I am sorry that this task cannot be updated temporarily. I temporarily closed this ISSUE and waited for some time to reopen it.
