### ISSUE TITLE
Print statement in train.language_model

### ISSUE THREAD

**Issue by sxjscience** [dmlc/gluon-nlp#968]
https://github.com/dmlc/gluon-nlp/blob/c3cac54083ca0da2faef764a37bb222806133a8b/src/gluonnlp/model/train/language_model.py#L305

https://github.com/dmlc/gluon-nlp/blob/c3cac54083ca0da2faef764a37bb222806133a8b/src/gluonnlp/model/train/language_model.py#L338

**Comment by eric-haibin-lin** [comment]
My bad. Checked in by accident...
