### ISSUE TITLE
Export for GPT-2

### ISSUE THREAD

**Issue by gigasquid** [dmlc/gluon-nlp#993]
## Description
I would like to be able to to export the GPT-2 model for text generation into MXNet Clojure. Would the same approach with the BERT export script work? https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/export.py

Looking for the best way to approach it - happy to help with this issue if I'm able.

**Comment by szha** [comment]
cc @sxjscience

**Comment by leezu** [comment]
It should be possible to make the `GPT2Model` a `HybridBlock` based on new additions to MXNet 1.6 (eg. `arange_like`). You're welcome to open a PR with the change.

**Comment by gigasquid** [comment]
Thanks for the feedback. I'll take a look at making the change 👍

**Comment by gigasquid** [comment]
I took a look at hybridizing the model and ran into problems. My experience with the Gluon/python code is probably not enough for me to tackle it on my own right now. 

If anyone else is interested in this feature, please feel free to pick it up.

Or maybe, I'll be able to circle back to address it in the future.

**Comment by eric-haibin-lin** [comment]
@gigasquid would you mind sharing the error you got?

**Comment by gigasquid** [comment]
@eric-haibin-lin - No problem. I didn't get too far but here is my wip attempt https://github.com/dmlc/gluon-nlp/compare/master...gigasquid:gpt2-export?expand=1

When I try to hybridize it gives the sensible error of 

```
Doing export for  gpt2_345m
Traceback (most recent call last):
  File "export.py", line 118, in <module>
    export()
  File "export.py", line 112, in export
    net(inputs)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 915, in forward
    return self._call_cached_op(x, *args)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 805, in _call_cached_op
    self._build_cache(*args)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 757, in _build_cache
    data, out = self._get_graph(*args)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 749, in _get_graph
    out = self.hybrid_forward(symbol, *grouped_inputs, **params)  # pylint: disable=no-value-for-parameter
  File "/Users/cmeier/workspace/deep-learning/gluon-nlp/scripts/text_generation/model/gpt.py", line 255, in hybrid_forward
    batch_size, seq_len = data.shape[0], data.shape[1]
AttributeError: 'Symbol' object has no attribute 'shape'
```

That's where I really didn't know where to go. I considered using `shape-array` https://mxnet.incubator.apache.org/api/python/docs/api/ndarray/ndarray.html#mxnet.ndarray.shape_array - but not sure if that was a good way to go. I didn't feel I had enough context/background to rewrite the layers for symbolic.

**Comment by leezu** [comment]
Thanks for clarifying the issue you met. Instead of using `shape-array`, it's possible to rewrite the forward function to not make explicit use of shape based on operators such as `F.arange_like`.

**Comment by leezu** [comment]
Will be fixed by https://github.com/dmlc/gluon-nlp/pull/1010

**Comment by gigasquid** [comment]
This is so awesome @leezu thanks 💯
