### ISSUE TITLE
Support Python 3.5

### ISSUE THREAD

**Issue by sxjscience** [dmlc/gluon-nlp#994]
We no longer support python 3.5

https://github.com/dmlc/gluon-nlp/blob/bfa5503e81ae53d26b9f202bce4fedcf09e47db4/setup.py#L35-L40 .

However, the default python3 in Ubuntu 16.04 still uses 3.5 and we should not drop the support.

**Comment by leezu** [comment]
For the record:
We need switch our tests on CI to test with Python 3.5.
For that, the conda env files in the `env` folder need to be changed.
It's not completely straightforward, as apparently some of the packages we currently have specified in the env files don't support Py 3.5 anymore.

**Comment by leezu** [comment]
> Python 3.5 had its last security bug-fix release on September 23rd, 2019 and no longer will be receiving security patches.

**Comment by sxjscience** [comment]
@leezu Do you think we should still support python3.5? I think dropping the support is not necessary.

**Comment by szha** [comment]
Given the discontinued maintenance, the cost of maintaining python 3.5 will gradually increase. Where does the rest of the world stand?

**Comment by sxjscience** [comment]
I successfully installed pytorch, Jax, tf2.0 in deep learning base AMI Ubuntu 16.04 (python 3.5) + MXNet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sxjscience** [comment]
Also, TVM supports python3.5 https://github.com/apache/incubator-tvm/pull/4250#event-2768263759

**Comment by leezu** [comment]
There was a consensus in August that MXNet can drop Python 3.5 support https://lists.apache.org/thread.html/d4b742f2507dfa55bad51b6e6be75e877ffefd717c2001f9cf037225@%3Cdev.mxnet.apache.org%3E

**Comment by sxjscience** [comment]
I think that thread is about dropping the support of python2. It’s not about Python3.5 v.s Python3.6. I recommend to wait before fully embracing python3.6. In fact, a large amount of our codebase is python3.5 compatible and we haven’t relied on many python3.6-only features.
________________________________

**Comment by leezu** [comment]
The question in that thread was which version to target as new minimum version, and there was consensus for Python 3.6.

In either way, currently there is no blocker to add Py3.5 support back to GluonNLP.

**Comment by sxjscience** [comment]
I think there was no consensus that we should drop python3.5 according to the MXNet discussion thread. Given that there is no blocker to add it back, we should better add it. Otherwise, we will lose the customers who are using Ubuntu 16.04. Let’s be less aggressive about version upgrade and we may revisit this next year.
________________________________

**Comment by leezu** [comment]
You can see that there was no negative response to https://lists.apache.org/thread.html/b74b189e7d5de3052d2aa5cc88824118bd5f1b90cf84bcf0801dca88@%3Cdev.mxnet.apache.org%3E and several supporting responses. Thus based on the mailinglist discussion there is currently consensus.

**Comment by sxjscience** [comment]
I think both Lieven and Marco in that thread expressed concerns about dropping 3.5. The main issue is Ubuntu 16.04. It’s just too early to drop python3.5 completely. We may do that together with MXNet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leezu** [comment]
Lieven asks to make sure we don't drop Py 3.5 support on old releases. Macro supported 3.6+

> From: Marco de Abreu <m...@gmail.com>
> Subject: Re: [Discuss] MXNet Python < 3.6 Support Deprecation
> Date: 2019/08/22 15:54:05
> List: dev@mxnet.apache.org
> 
> +1 for 3.6+

In either way, my point is that if you feel we need to follow Ubuntu's release schedule instead of Pythons release schedule, you should state that opinion on the mailinglist as well.

**Comment by sxjscience** [comment]
Sure. I think that if there is a future vote about dropping 3.5, I'll veto that.

**Comment by sxjscience** [comment]
@dmlc/gluon-nlp-committers  What do you think?

**Comment by leezu** [comment]
There is no need for a future vote, as currently there is consensus on the mailinglist. You need to express your concerns on the mailinglist.

**Comment by leezu** [comment]
Just reply to the thread in question

**Comment by leezu** [comment]
http://theapacheway.com/on-list/

> 
> If it didn’t happen on the mailing list, it didn’t happen.
> 
> A key motto at Apache is: “If it didn’t happen on the mailing list, it didn’t happen.”

**Comment by sxjscience** [comment]
Thanks, I think I should be more active on the mailing list.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leezu** [comment]
Deep Learning AMI is now based on Ubuntu 18.04
https://aws.amazon.com/marketplace/search/results?x=0&y=0&searchTerms=dlami

**Comment by sxjscience** [comment]
We can stick to python3.6 when we decide to use some python3.6-specific features. For now, it's safe to support python3.5 so why not? python3.5 is also supported in D2L: https://github.com/d2l-ai/d2l-en/commit/c9b9968879e5c6f8e792320c9cb2371cf393e964

**Comment by leezu** [comment]
It's fine to add support. I'm just adding the context as your initial concern was with DL AMI.
