### ISSUE TITLE
How does weight tying work between src_embed and tgt_embed in NMTModel?

### ISSUE THREAD

**Issue by zeeshansayyed** [dmlc/gluon-nlp#996]
Hi, I have a question regarding weight tying in the encoder and decoder embedding matrix of the NMTModel. Consider [these lines](https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/model/translation.py#L84-L130) of the NMTModel class.

As has been described in Issue [#7785](https://github.com/apache/incubator-mxnet/issues/7785) of mxnet repo and [this section](https://d2l.ai/chapter_deep-learning-computation/parameters.html#tied-parameters) in d2l.ai, we usually do it by calling the `params` argument of the layer new layer and pass the params of the layer from which we want to tie.

But in the NMTModel class referenced above, we are simply assigning the references in line 98 and 101 as `self.src_embed = src_embed` and `self.tgt_embed = self.src_embed`.

_Is this also a valid way of tying weights?_

Note: I have also opened an [issue](https://github.com/apache/incubator-mxnet/issues/16684) in the mxnet repo since I didn't know which was the right place to ask. I will close the one which is not needed.

**Comment by leezu** [comment]
Hi @zeeshansayyed

**Comment by zeeshansayyed** [comment]
Thank you.
